/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtNetwork.h"

#line 28 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtNetwork/qssl.sip"
#include <qssl.h>
#line 29 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtNetwork/sipQtNetworkQSsl.cpp"


static sipEnumMemberDef enummembers_QSsl[] = {
    {sipName_AnyProtocol, static_cast<int>( ::QSsl::AnyProtocol), 110},
    {sipName_Der, static_cast<int>( ::QSsl::Der), 105},
    {sipName_DnsEntry, static_cast<int>( ::QSsl::DnsEntry), 104},
    {sipName_Dsa, static_cast<int>( ::QSsl::Dsa), 106},
    {sipName_Ec, static_cast<int>( ::QSsl::Ec), 106},
    {sipName_EmailEntry, static_cast<int>( ::QSsl::EmailEntry), 104},
    {sipName_Opaque, static_cast<int>( ::QSsl::Opaque), 106},
    {sipName_Pem, static_cast<int>( ::QSsl::Pem), 105},
    {sipName_PrivateKey, static_cast<int>( ::QSsl::PrivateKey), 107},
    {sipName_PublicKey, static_cast<int>( ::QSsl::PublicKey), 107},
    {sipName_Rsa, static_cast<int>( ::QSsl::Rsa), 106},
    {sipName_SecureProtocols, static_cast<int>( ::QSsl::SecureProtocols), 110},
    {sipName_SslOptionDisableCompression, static_cast<int>( ::QSsl::SslOptionDisableCompression), 108},
    {sipName_SslOptionDisableEmptyFragments, static_cast<int>( ::QSsl::SslOptionDisableEmptyFragments), 108},
    {sipName_SslOptionDisableLegacyRenegotiation, static_cast<int>( ::QSsl::SslOptionDisableLegacyRenegotiation), 108},
    {sipName_SslOptionDisableServerCipherPreference, static_cast<int>( ::QSsl::SslOptionDisableServerCipherPreference), 108},
    {sipName_SslOptionDisableServerNameIndication, static_cast<int>( ::QSsl::SslOptionDisableServerNameIndication), 108},
    {sipName_SslOptionDisableSessionPersistence, static_cast<int>( ::QSsl::SslOptionDisableSessionPersistence), 108},
    {sipName_SslOptionDisableSessionSharing, static_cast<int>( ::QSsl::SslOptionDisableSessionSharing), 108},
    {sipName_SslOptionDisableSessionTickets, static_cast<int>( ::QSsl::SslOptionDisableSessionTickets), 108},
    {sipName_SslV2, static_cast<int>( ::QSsl::SslV2), 110},
    {sipName_SslV3, static_cast<int>( ::QSsl::SslV3), 110},
    {sipName_TlsV1SslV3, static_cast<int>( ::QSsl::TlsV1SslV3), 110},
    {sipName_TlsV1_0, static_cast<int>( ::QSsl::TlsV1_0), 110},
    {sipName_TlsV1_0OrLater, static_cast<int>( ::QSsl::TlsV1_0OrLater), 110},
    {sipName_TlsV1_1, static_cast<int>( ::QSsl::TlsV1_1), 110},
    {sipName_TlsV1_1OrLater, static_cast<int>( ::QSsl::TlsV1_1OrLater), 110},
    {sipName_TlsV1_2, static_cast<int>( ::QSsl::TlsV1_2), 110},
    {sipName_TlsV1_2OrLater, static_cast<int>( ::QSsl::TlsV1_2OrLater), 110},
    {sipName_UnknownProtocol, static_cast<int>( ::QSsl::UnknownProtocol), 110},
};


static pyqt5ClassPluginDef plugin_QSsl = {
    0,
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtNetwork_QSsl = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_NAMESPACE,
        sipNameNr_QSsl,
        {0},
        &plugin_QSsl
    },
    {
        sipNameNr_QSsl,
        {0, 0, 1},
        0, 0,
        30, enummembers_QSsl,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    0,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};
