/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtWebEngineWidgets.h"

#line 28 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtWebEngineWidgets/qwebenginedownloaditem.sip"
#include <qwebenginedownloaditem.h>
#line 29 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"

#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 33 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 96 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 36 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 39 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 42 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 247 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 45 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 235 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 48 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 51 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 54 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 38 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 57 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 30 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 60 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 149 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 63 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 66 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 69 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 72 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 75 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 78 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 81 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtWebEngineWidgets/sipQtWebEngineWidgetsQWebEngineDownloadItem.cpp"


PyDoc_STRVAR(doc_QWebEngineDownloadItem_id, "id(self) -> int");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_id(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_id(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::quint32 sipRes;

            sipRes = sipCpp->id();

            return PyLong_FromUnsignedLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_id, doc_QWebEngineDownloadItem_id);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_state, "state(self) -> QWebEngineDownloadItem.DownloadState");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_state(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_state(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QWebEngineDownloadItem::DownloadState sipRes;

            sipRes = sipCpp->state();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QWebEngineDownloadItem_DownloadState);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_state, doc_QWebEngineDownloadItem_state);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_totalBytes, "totalBytes(self) -> int");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_totalBytes(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_totalBytes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::qint64 sipRes;

            sipRes = sipCpp->totalBytes();

            return PyLong_FromLongLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_totalBytes, doc_QWebEngineDownloadItem_totalBytes);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_receivedBytes, "receivedBytes(self) -> int");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_receivedBytes(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_receivedBytes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::qint64 sipRes;

            sipRes = sipCpp->receivedBytes();

            return PyLong_FromLongLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_receivedBytes, doc_QWebEngineDownloadItem_receivedBytes);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_url, "url(self) -> QUrl");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_url(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_url(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QUrl*sipRes;

            sipRes = new  ::QUrl(sipCpp->url());

            return sipConvertFromNewType(sipRes,sipType_QUrl,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_url, doc_QWebEngineDownloadItem_url);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_path, "path(self) -> str");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_path(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_path(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QString*sipRes;

            sipRes = new  ::QString(sipCpp->path());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_path, doc_QWebEngineDownloadItem_path);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_setPath, "setPath(self, str)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_setPath(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_setPath(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QString* a0;
        int a0State = 0;
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp, sipType_QString,&a0, &a0State))
        {
            sipCpp->setPath(*a0);
            sipReleaseType(a0,sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_setPath, doc_QWebEngineDownloadItem_setPath);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_isFinished, "isFinished(self) -> bool");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_isFinished(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_isFinished(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isFinished();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_isFinished, doc_QWebEngineDownloadItem_isFinished);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_accept, "accept(self)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_accept(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_accept(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            sipCpp->accept();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_accept, doc_QWebEngineDownloadItem_accept);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_cancel, "cancel(self)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_cancel(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_cancel(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            sipCpp->cancel();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_cancel, doc_QWebEngineDownloadItem_cancel);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_mimeType, "mimeType(self) -> str");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_mimeType(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_mimeType(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QString*sipRes;

            sipRes = new  ::QString(sipCpp->mimeType());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_mimeType, doc_QWebEngineDownloadItem_mimeType);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_savePageFormat, "savePageFormat(self) -> QWebEngineDownloadItem.SavePageFormat");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_savePageFormat(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_savePageFormat(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QWebEngineDownloadItem::SavePageFormat sipRes;

            sipRes = sipCpp->savePageFormat();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QWebEngineDownloadItem_SavePageFormat);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_savePageFormat, doc_QWebEngineDownloadItem_savePageFormat);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_setSavePageFormat, "setSavePageFormat(self, QWebEngineDownloadItem.SavePageFormat)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_setSavePageFormat(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_setSavePageFormat(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QWebEngineDownloadItem::SavePageFormat a0;
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp, sipType_QWebEngineDownloadItem_SavePageFormat, &a0))
        {
            sipCpp->setSavePageFormat(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_setSavePageFormat, doc_QWebEngineDownloadItem_setSavePageFormat);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_type, "type(self) -> QWebEngineDownloadItem.DownloadType");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_type(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_type(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QWebEngineDownloadItem::DownloadType sipRes;

            sipRes = sipCpp->type();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QWebEngineDownloadItem_DownloadType);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_type, doc_QWebEngineDownloadItem_type);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_interruptReason, "interruptReason(self) -> QWebEngineDownloadItem.DownloadInterruptReason");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_interruptReason(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_interruptReason(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QWebEngineDownloadItem::DownloadInterruptReason sipRes;

            sipRes = sipCpp->interruptReason();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QWebEngineDownloadItem_DownloadInterruptReason);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_interruptReason, doc_QWebEngineDownloadItem_interruptReason);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_interruptReasonString, "interruptReasonString(self) -> str");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_interruptReasonString(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_interruptReasonString(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
             ::QString*sipRes;

            sipRes = new  ::QString(sipCpp->interruptReasonString());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_interruptReasonString, doc_QWebEngineDownloadItem_interruptReasonString);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_isPaused, "isPaused(self) -> bool");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_isPaused(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_isPaused(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isPaused();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_isPaused, doc_QWebEngineDownloadItem_isPaused);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_pause, "pause(self)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_pause(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_pause(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            sipCpp->pause();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_pause, doc_QWebEngineDownloadItem_pause);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_resume, "resume(self)");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_resume(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_resume(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            sipCpp->resume();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_resume, doc_QWebEngineDownloadItem_resume);

    return NULL;
}


PyDoc_STRVAR(doc_QWebEngineDownloadItem_isSavePageDownload, "isSavePageDownload(self) -> bool");

extern "C" {static PyObject *meth_QWebEngineDownloadItem_isSavePageDownload(PyObject *, PyObject *);}
static PyObject *meth_QWebEngineDownloadItem_isSavePageDownload(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QWebEngineDownloadItem *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QWebEngineDownloadItem, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isSavePageDownload();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QWebEngineDownloadItem, sipName_isSavePageDownload, doc_QWebEngineDownloadItem_isSavePageDownload);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QWebEngineDownloadItem(void *, const sipTypeDef *);}
static void *cast_QWebEngineDownloadItem(void *sipCppV, const sipTypeDef *targetType)
{
     ::QWebEngineDownloadItem *sipCpp = reinterpret_cast< ::QWebEngineDownloadItem *>(sipCppV);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QWebEngineDownloadItem(void *, int);}
static void release_QWebEngineDownloadItem(void *sipCppV, int)
{
     ::QWebEngineDownloadItem *sipCpp = reinterpret_cast< ::QWebEngineDownloadItem *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QWebEngineDownloadItem(sipSimpleWrapper *);}
static void dealloc_QWebEngineDownloadItem(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QWebEngineDownloadItem(sipGetAddress(sipSelf), 0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QWebEngineDownloadItem[] = {{7, 0, 1}};


static PyMethodDef methods_QWebEngineDownloadItem[] = {
    {SIP_MLNAME_CAST(sipName_accept), meth_QWebEngineDownloadItem_accept, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_accept)},
    {SIP_MLNAME_CAST(sipName_cancel), meth_QWebEngineDownloadItem_cancel, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_cancel)},
    {SIP_MLNAME_CAST(sipName_id), meth_QWebEngineDownloadItem_id, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_id)},
    {SIP_MLNAME_CAST(sipName_interruptReason), meth_QWebEngineDownloadItem_interruptReason, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_interruptReason)},
    {SIP_MLNAME_CAST(sipName_interruptReasonString), meth_QWebEngineDownloadItem_interruptReasonString, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_interruptReasonString)},
    {SIP_MLNAME_CAST(sipName_isFinished), meth_QWebEngineDownloadItem_isFinished, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_isFinished)},
    {SIP_MLNAME_CAST(sipName_isPaused), meth_QWebEngineDownloadItem_isPaused, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_isPaused)},
    {SIP_MLNAME_CAST(sipName_isSavePageDownload), meth_QWebEngineDownloadItem_isSavePageDownload, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_isSavePageDownload)},
    {SIP_MLNAME_CAST(sipName_mimeType), meth_QWebEngineDownloadItem_mimeType, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_mimeType)},
    {SIP_MLNAME_CAST(sipName_path), meth_QWebEngineDownloadItem_path, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_path)},
    {SIP_MLNAME_CAST(sipName_pause), meth_QWebEngineDownloadItem_pause, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_pause)},
    {SIP_MLNAME_CAST(sipName_receivedBytes), meth_QWebEngineDownloadItem_receivedBytes, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_receivedBytes)},
    {SIP_MLNAME_CAST(sipName_resume), meth_QWebEngineDownloadItem_resume, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_resume)},
    {SIP_MLNAME_CAST(sipName_savePageFormat), meth_QWebEngineDownloadItem_savePageFormat, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_savePageFormat)},
    {SIP_MLNAME_CAST(sipName_setPath), meth_QWebEngineDownloadItem_setPath, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_setPath)},
    {SIP_MLNAME_CAST(sipName_setSavePageFormat), meth_QWebEngineDownloadItem_setSavePageFormat, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_setSavePageFormat)},
    {SIP_MLNAME_CAST(sipName_state), meth_QWebEngineDownloadItem_state, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_state)},
    {SIP_MLNAME_CAST(sipName_totalBytes), meth_QWebEngineDownloadItem_totalBytes, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_totalBytes)},
    {SIP_MLNAME_CAST(sipName_type), meth_QWebEngineDownloadItem_type, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_type)},
    {SIP_MLNAME_CAST(sipName_url), meth_QWebEngineDownloadItem_url, METH_VARARGS, SIP_MLDOC_CAST(doc_QWebEngineDownloadItem_url)}
};

static sipEnumMemberDef enummembers_QWebEngineDownloadItem[] = {
    {sipName_Attachment, static_cast<int>( ::QWebEngineDownloadItem::Attachment), 13},
    {sipName_CompleteHtmlSaveFormat, static_cast<int>( ::QWebEngineDownloadItem::CompleteHtmlSaveFormat), 14},
    {sipName_DownloadAttribute, static_cast<int>( ::QWebEngineDownloadItem::DownloadAttribute), 13},
    {sipName_DownloadCancelled, static_cast<int>( ::QWebEngineDownloadItem::DownloadCancelled), 12},
    {sipName_DownloadCompleted, static_cast<int>( ::QWebEngineDownloadItem::DownloadCompleted), 12},
    {sipName_DownloadInProgress, static_cast<int>( ::QWebEngineDownloadItem::DownloadInProgress), 12},
    {sipName_DownloadInterrupted, static_cast<int>( ::QWebEngineDownloadItem::DownloadInterrupted), 12},
    {sipName_DownloadRequested, static_cast<int>( ::QWebEngineDownloadItem::DownloadRequested), 12},
    {sipName_FileAccessDenied, static_cast<int>( ::QWebEngineDownloadItem::FileAccessDenied), 11},
    {sipName_FileBlocked, static_cast<int>( ::QWebEngineDownloadItem::FileBlocked), 11},
    {sipName_FileFailed, static_cast<int>( ::QWebEngineDownloadItem::FileFailed), 11},
    {sipName_FileHashMismatch, static_cast<int>( ::QWebEngineDownloadItem::FileHashMismatch), 11},
    {sipName_FileNameTooLong, static_cast<int>( ::QWebEngineDownloadItem::FileNameTooLong), 11},
    {sipName_FileNoSpace, static_cast<int>( ::QWebEngineDownloadItem::FileNoSpace), 11},
    {sipName_FileSecurityCheckFailed, static_cast<int>( ::QWebEngineDownloadItem::FileSecurityCheckFailed), 11},
    {sipName_FileTooLarge, static_cast<int>( ::QWebEngineDownloadItem::FileTooLarge), 11},
    {sipName_FileTooShort, static_cast<int>( ::QWebEngineDownloadItem::FileTooShort), 11},
    {sipName_FileTransientError, static_cast<int>( ::QWebEngineDownloadItem::FileTransientError), 11},
    {sipName_FileVirusInfected, static_cast<int>( ::QWebEngineDownloadItem::FileVirusInfected), 11},
    {sipName_MimeHtmlSaveFormat, static_cast<int>( ::QWebEngineDownloadItem::MimeHtmlSaveFormat), 14},
    {sipName_NetworkDisconnected, static_cast<int>( ::QWebEngineDownloadItem::NetworkDisconnected), 11},
    {sipName_NetworkFailed, static_cast<int>( ::QWebEngineDownloadItem::NetworkFailed), 11},
    {sipName_NetworkInvalidRequest, static_cast<int>( ::QWebEngineDownloadItem::NetworkInvalidRequest), 11},
    {sipName_NetworkServerDown, static_cast<int>( ::QWebEngineDownloadItem::NetworkServerDown), 11},
    {sipName_NetworkTimeout, static_cast<int>( ::QWebEngineDownloadItem::NetworkTimeout), 11},
    {sipName_NoReason, static_cast<int>( ::QWebEngineDownloadItem::NoReason), 11},
    {sipName_SavePage, static_cast<int>( ::QWebEngineDownloadItem::SavePage), 13},
    {sipName_ServerBadContent, static_cast<int>( ::QWebEngineDownloadItem::ServerBadContent), 11},
    {sipName_ServerCertProblem, static_cast<int>( ::QWebEngineDownloadItem::ServerCertProblem), 11},
    {sipName_ServerFailed, static_cast<int>( ::QWebEngineDownloadItem::ServerFailed), 11},
    {sipName_ServerForbidden, static_cast<int>( ::QWebEngineDownloadItem::ServerForbidden), 11},
    {sipName_ServerUnauthorized, static_cast<int>( ::QWebEngineDownloadItem::ServerUnauthorized), 11},
    {sipName_ServerUnreachable, static_cast<int>( ::QWebEngineDownloadItem::ServerUnreachable), 11},
    {sipName_SingleHtmlSaveFormat, static_cast<int>( ::QWebEngineDownloadItem::SingleHtmlSaveFormat), 14},
    {sipName_UnknownSaveFormat, static_cast<int>( ::QWebEngineDownloadItem::UnknownSaveFormat), 14},
    {sipName_UserCanceled, static_cast<int>( ::QWebEngineDownloadItem::UserCanceled), 11},
    {sipName_UserRequested, static_cast<int>( ::QWebEngineDownloadItem::UserRequested), 13},
};


/* Define this type's signals. */
static const pyqt5QtSignal signals_QWebEngineDownloadItem[] = {
    {"isPausedChanged(bool)", "\1isPausedChanged(self, bool)", 0, 0},
    {"downloadProgress(qint64,qint64)", "\1downloadProgress(self, int, int)", 0, 0},
    {"stateChanged(QWebEngineDownloadItem::DownloadState)", "\1stateChanged(self, QWebEngineDownloadItem.DownloadState)", 0, 0},
    {"finished()", "\1finished(self)", 0, 0},
    {0, 0, 0, 0}
};


static pyqt5ClassPluginDef plugin_QWebEngineDownloadItem = {
    & ::QWebEngineDownloadItem::staticMetaObject,
    0,
    signals_QWebEngineDownloadItem,
    0
};


sipClassTypeDef sipTypeDef_QtWebEngineWidgets_QWebEngineDownloadItem = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QWebEngineDownloadItem,
        {0},
        &plugin_QWebEngineDownloadItem
    },
    {
        sipNameNr_QWebEngineDownloadItem,
        {0, 0, 1},
        20, methods_QWebEngineDownloadItem,
        37, enummembers_QWebEngineDownloadItem,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QWebEngineDownloadItem,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QWebEngineDownloadItem,
    0,
    0,
    0,
    release_QWebEngineDownloadItem,
    cast_QWebEngineDownloadItem,
    0,
    0,
    0,
    0,
    0,
    0
};
