/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtMultimediaWidgetsAPI_H
#define _QtMultimediaWidgetsAPI_H

#if !defined(Py_LIMITED_API)
#define Py_LIMITED_API
#endif

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_MACX


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_PyQt5_QtMultimediaWidgets 0
#define sipName_PyQt5_QtMultimediaWidgets &sipStrings_QtMultimediaWidgets[0]
#define sipNameNr_mouseDoubleClickEvent 26
#define sipName_mouseDoubleClickEvent &sipStrings_QtMultimediaWidgets[26]
#define sipNameNr_setAspectRatioMode 48
#define sipName_setAspectRatioMode &sipStrings_QtMultimediaWidgets[48]
#define sipNameNr_focusNextPrevChild 67
#define sipName_focusNextPrevChild &sipStrings_QtMultimediaWidgets[67]
#define sipNameNr_QGraphicsVideoItem 86
#define sipName_QGraphicsVideoItem &sipStrings_QtMultimediaWidgets[86]
#define sipNameNr_saturationChanged 105
#define sipName_saturationChanged &sipStrings_QtMultimediaWidgets[105]
#define sipNameNr_brightnessChanged 123
#define sipName_brightnessChanged &sipStrings_QtMultimediaWidgets[123]
#define sipNameNr_fullScreenChanged 141
#define sipName_fullScreenChanged &sipStrings_QtMultimediaWidgets[141]
#define sipNameNr_nativeSizeChanged 159
#define sipName_nativeSizeChanged &sipStrings_QtMultimediaWidgets[159]
#define sipNameNr_QCameraViewfinder 177
#define sipName_QCameraViewfinder &sipStrings_QtMultimediaWidgets[177]
#define sipNameNr_hasHeightForWidth 195
#define sipName_hasHeightForWidth &sipStrings_QtMultimediaWidgets[195]
#define sipNameNr_mouseReleaseEvent 213
#define sipName_mouseReleaseEvent &sipStrings_QtMultimediaWidgets[213]
#define sipNameNr_sceneEventFilter 231
#define sipName_sceneEventFilter &sipStrings_QtMultimediaWidgets[231]
#define sipNameNr_collidesWithPath 248
#define sipName_collidesWithPath &sipStrings_QtMultimediaWidgets[248]
#define sipNameNr_collidesWithItem 265
#define sipName_collidesWithItem &sipStrings_QtMultimediaWidgets[265]
#define sipNameNr_contextMenuEvent 282
#define sipName_contextMenuEvent &sipStrings_QtMultimediaWidgets[282]
#define sipNameNr_inputMethodEvent 299
#define sipName_inputMethodEvent &sipStrings_QtMultimediaWidgets[299]
#define sipNameNr_inputMethodQuery 316
#define sipName_inputMethodQuery &sipStrings_QtMultimediaWidgets[316]
#define sipNameNr_disconnectNotify 333
#define sipName_disconnectNotify &sipStrings_QtMultimediaWidgets[333]
#define sipNameNr_contrastChanged 350
#define sipName_contrastChanged &sipStrings_QtMultimediaWidgets[350]
#define sipNameNr_hoverLeaveEvent 366
#define sipName_hoverLeaveEvent &sipStrings_QtMultimediaWidgets[366]
#define sipNameNr_hoverEnterEvent 382
#define sipName_hoverEnterEvent &sipStrings_QtMultimediaWidgets[382]
#define sipNameNr_minimumSizeHint 398
#define sipName_minimumSizeHint &sipStrings_QtMultimediaWidgets[398]
#define sipNameNr_mousePressEvent 414
#define sipName_mousePressEvent &sipStrings_QtMultimediaWidgets[414]
#define sipNameNr_keyReleaseEvent 430
#define sipName_keyReleaseEvent &sipStrings_QtMultimediaWidgets[430]
#define sipNameNr_deviceTransform 446
#define sipName_deviceTransform &sipStrings_QtMultimediaWidgets[446]
#define sipNameNr_internal_format 462
#define sipName_internal_format &sipStrings_QtMultimediaWidgets[462]
#define sipNameNr_aspectRatioMode 478
#define sipName_aspectRatioMode &sipStrings_QtMultimediaWidgets[478]
#define sipNameNr_hoverMoveEvent 494
#define sipName_hoverMoveEvent &sipStrings_QtMultimediaWidgets[494]
#define sipNameNr_heightForWidth 509
#define sipName_heightForWidth &sipStrings_QtMultimediaWidgets[509]
#define sipNameNr_dragLeaveEvent 524
#define sipName_dragLeaveEvent &sipStrings_QtMultimediaWidgets[524]
#define sipNameNr_dragEnterEvent 539
#define sipName_dragEnterEvent &sipStrings_QtMultimediaWidgets[539]
#define sipNameNr_setMediaObject 554
#define sipName_setMediaObject &sipStrings_QtMultimediaWidgets[554]
#define sipNameNr_mouseMoveEvent 569
#define sipName_mouseMoveEvent &sipStrings_QtMultimediaWidgets[569]
#define sipNameNr_setFullScreen 584
#define sipName_setFullScreen &sipStrings_QtMultimediaWidgets[584]
#define sipNameNr_sharedPainter 598
#define sipName_sharedPainter &sipStrings_QtMultimediaWidgets[598]
#define sipNameNr_dragMoveEvent 612
#define sipName_dragMoveEvent &sipStrings_QtMultimediaWidgets[612]
#define sipNameNr_setBrightness 626
#define sipName_setBrightness &sipStrings_QtMultimediaWidgets[626]
#define sipNameNr_setSaturation 640
#define sipName_setSaturation &sipStrings_QtMultimediaWidgets[640]
#define sipNameNr_keyPressEvent 654
#define sipName_keyPressEvent &sipStrings_QtMultimediaWidgets[654]
#define sipNameNr_focusOutEvent 668
#define sipName_focusOutEvent &sipStrings_QtMultimediaWidgets[668]
#define sipNameNr_transformMode 682
#define sipName_transformMode &sipStrings_QtMultimediaWidgets[682]
#define sipNameNr_connectNotify 336
#define sipName_connectNotify &sipStrings_QtMultimediaWidgets[336]
#define sipNameNr_sourceRegion 696
#define sipName_sourceRegion &sipStrings_QtMultimediaWidgets[696]
#define sipNameNr_targetOffset 709
#define sipName_targetOffset &sipStrings_QtMultimediaWidgets[709]
#define sipNameNr_isObscuredBy 722
#define sipName_isObscuredBy &sipStrings_QtMultimediaWidgets[722]
#define sipNameNr_midLineWidth 735
#define sipName_midLineWidth &sipStrings_QtMultimediaWidgets[735]
#define sipNameNr_QVideoWidget 748
#define sipName_QVideoWidget &sipStrings_QtMultimediaWidgets[748]
#define sipNameNr_focusInEvent 761
#define sipName_focusInEvent &sipStrings_QtMultimediaWidgets[761]
#define sipNameNr_boundingRect 774
#define sipName_boundingRect &sipStrings_QtMultimediaWidgets[774]
#define sipNameNr_initPainter 787
#define sipName_initPainter &sipStrings_QtMultimediaWidgets[787]
#define sipNameNr_nativeEvent 799
#define sipName_nativeEvent &sipStrings_QtMultimediaWidgets[799]
#define sipNameNr_actionEvent 811
#define sipName_actionEvent &sipStrings_QtMultimediaWidgets[811]
#define sipNameNr_changeEvent 823
#define sipName_changeEvent &sipStrings_QtMultimediaWidgets[823]
#define sipNameNr_setContrast 835
#define sipName_setContrast &sipStrings_QtMultimediaWidgets[835]
#define sipNameNr_mediaObject 847
#define sipName_mediaObject &sipStrings_QtMultimediaWidgets[847]
#define sipNameNr_tabletEvent 859
#define sipName_tabletEvent &sipStrings_QtMultimediaWidgets[859]
#define sipNameNr_matchPolicy 871
#define sipName_matchPolicy &sipStrings_QtMultimediaWidgets[871]
#define sipNameNr_resizeEvent 883
#define sipName_resizeEvent &sipStrings_QtMultimediaWidgets[883]
#define sipNameNr_paintEngine 895
#define sipName_paintEngine &sipStrings_QtMultimediaWidgets[895]
#define sipNameNr_customEvent 907
#define sipName_customEvent &sipStrings_QtMultimediaWidgets[907]
#define sipNameNr_eventFilter 919
#define sipName_eventFilter &sipStrings_QtMultimediaWidgets[919]
#define sipNameNr_hueChanged 931
#define sipName_hueChanged &sipStrings_QtMultimediaWidgets[931]
#define sipNameNr_nativeSize 942
#define sipName_nativeSize &sipStrings_QtMultimediaWidgets[942]
#define sipNameNr_enterEvent 953
#define sipName_enterEvent &sipStrings_QtMultimediaWidgets[953]
#define sipNameNr_leaveEvent 964
#define sipName_leaveEvent &sipStrings_QtMultimediaWidgets[964]
#define sipNameNr_sceneEvent 975
#define sipName_sceneEvent &sipStrings_QtMultimediaWidgets[975]
#define sipNameNr_itemChange 986
#define sipName_itemChange &sipStrings_QtMultimediaWidgets[986]
#define sipNameNr_opaqueArea 997
#define sipName_opaqueArea &sipStrings_QtMultimediaWidgets[997]
#define sipNameNr_closeEvent 1008
#define sipName_closeEvent &sipStrings_QtMultimediaWidgets[1008]
#define sipNameNr_brightness 1019
#define sipName_brightness &sipStrings_QtMultimediaWidgets[1019]
#define sipNameNr_wheelEvent 1030
#define sipName_wheelEvent &sipStrings_QtMultimediaWidgets[1030]
#define sipNameNr_paintEvent 1041
#define sipName_paintEvent &sipStrings_QtMultimediaWidgets[1041]
#define sipNameNr_genMipMaps 1052
#define sipName_genMipMaps &sipStrings_QtMultimediaWidgets[1052]
#define sipNameNr_setVisible 1063
#define sipName_setVisible &sipStrings_QtMultimediaWidgets[1063]
#define sipNameNr_saturation 1074
#define sipName_saturation &sipStrings_QtMultimediaWidgets[1074]
#define sipNameNr_childEvent 1085
#define sipName_childEvent &sipStrings_QtMultimediaWidgets[1085]
#define sipNameNr_timerEvent 1096
#define sipName_timerEvent &sipStrings_QtMultimediaWidgets[1096]
#define sipNameNr_dropEvent 1107
#define sipName_dropEvent &sipStrings_QtMultimediaWidgets[1107]
#define sipNameNr_hideEvent 1117
#define sipName_hideEvent &sipStrings_QtMultimediaWidgets[1117]
#define sipNameNr_showEvent 1127
#define sipName_showEvent &sipStrings_QtMultimediaWidgets[1127]
#define sipNameNr_moveEvent 1137
#define sipName_moveEvent &sipStrings_QtMultimediaWidgets[1137]
#define sipNameNr_operation 1147
#define sipName_operation &sipStrings_QtMultimediaWidgets[1147]
#define sipNameNr_setOffset 1157
#define sipName_setOffset &sipStrings_QtMultimediaWidgets[1157]
#define sipNameNr_lineWidth 1167
#define sipName_lineWidth &sipStrings_QtMultimediaWidgets[1167]
#define sipNameNr_directory 1177
#define sipName_directory &sipStrings_QtMultimediaWidgets[1177]
#define sipNameNr_alignment 1187
#define sipName_alignment &sipStrings_QtMultimediaWidgets[1187]
#define sipNameNr_precision 1197
#define sipName_precision &sipStrings_QtMultimediaWidgets[1197]
#define sipNameNr_shortcut 1207
#define sipName_shortcut &sipStrings_QtMultimediaWidgets[1207]
#define sipNameNr_contrast 1216
#define sipName_contrast &sipStrings_QtMultimediaWidgets[1216]
#define sipNameNr_protocol 1225
#define sipName_protocol &sipStrings_QtMultimediaWidgets[1225]
#define sipNameNr_userData 1234
#define sipName_userData &sipStrings_QtMultimediaWidgets[1234]
#define sipNameNr_encoding 1243
#define sipName_encoding &sipStrings_QtMultimediaWidgets[1243]
#define sipNameNr_sizeHint 1252
#define sipName_sizeHint &sipStrings_QtMultimediaWidgets[1252]
#define sipNameNr_fillRule 1261
#define sipName_fillRule &sipStrings_QtMultimediaWidgets[1261]
#define sipNameNr_tabArray 1270
#define sipName_tabArray &sipStrings_QtMultimediaWidgets[1270]
#define sipNameNr_tabStops 1279
#define sipName_tabStops &sipStrings_QtMultimediaWidgets[1279]
#define sipNameNr_nameType 1288
#define sipName_nameType &sipStrings_QtMultimediaWidgets[1288]
#define sipNameNr_position 1297
#define sipName_position &sipStrings_QtMultimediaWidgets[1297]
#define sipNameNr_contains 1306
#define sipName_contains &sipStrings_QtMultimediaWidgets[1306]
#define sipNameNr_advance 1315
#define sipName_advance &sipStrings_QtMultimediaWidgets[1315]
#define sipNameNr_yMargin 1323
#define sipName_yMargin &sipStrings_QtMultimediaWidgets[1323]
#define sipNameNr_xMargin 1331
#define sipName_xMargin &sipStrings_QtMultimediaWidgets[1331]
#define sipNameNr_exposed 1339
#define sipName_exposed &sipStrings_QtMultimediaWidgets[1339]
#define sipNameNr_buffers 1347
#define sipName_buffers &sipStrings_QtMultimediaWidgets[1347]
#define sipNameNr_sources 1355
#define sipName_sources &sipStrings_QtMultimediaWidgets[1355]
#define sipNameNr_quality 1363
#define sipName_quality &sipStrings_QtMultimediaWidgets[1363]
#define sipNameNr_devType 1371
#define sipName_devType &sipStrings_QtMultimediaWidgets[1371]
#define sipNameNr_setSize 1379
#define sipName_setSize &sipStrings_QtMultimediaWidgets[1379]
#define sipNameNr_filters 1387
#define sipName_filters &sipStrings_QtMultimediaWidgets[1387]
#define sipNameNr_options 1395
#define sipName_options &sipStrings_QtMultimediaWidgets[1395]
#define sipNameNr_setHue 1403
#define sipName_setHue &sipStrings_QtMultimediaWidgets[1403]
#define sipNameNr_sunken 1410
#define sipName_sunken &sipStrings_QtMultimediaWidgets[1410]
#define sipNameNr_layers 1417
#define sipName_layers &sipStrings_QtMultimediaWidgets[1417]
#define sipNameNr_stride 1424
#define sipName_stride &sipStrings_QtMultimediaWidgets[1424]
#define sipNameNr_metric 1431
#define sipName_metric &sipStrings_QtMultimediaWidgets[1431]
#define sipNameNr_widget 1438
#define sipName_widget &sipStrings_QtMultimediaWidgets[1438]
#define sipNameNr_proper 1445
#define sipName_proper &sipStrings_QtMultimediaWidgets[1445]
#define sipNameNr_value9 1452
#define sipName_value9 &sipStrings_QtMultimediaWidgets[1452]
#define sipNameNr_value8 1459
#define sipName_value8 &sipStrings_QtMultimediaWidgets[1459]
#define sipNameNr_value7 1466
#define sipName_value7 &sipStrings_QtMultimediaWidgets[1466]
#define sipNameNr_value6 1473
#define sipName_value6 &sipStrings_QtMultimediaWidgets[1473]
#define sipNameNr_value5 1480
#define sipName_value5 &sipStrings_QtMultimediaWidgets[1480]
#define sipNameNr_value4 1487
#define sipName_value4 &sipStrings_QtMultimediaWidgets[1487]
#define sipNameNr_value3 1494
#define sipName_value3 &sipStrings_QtMultimediaWidgets[1494]
#define sipNameNr_value2 1501
#define sipName_value2 &sipStrings_QtMultimediaWidgets[1501]
#define sipNameNr_value1 1508
#define sipName_value1 &sipStrings_QtMultimediaWidgets[1508]
#define sipNameNr_value0 1515
#define sipName_value0 &sipStrings_QtMultimediaWidgets[1515]
#define sipNameNr_symbol 1522
#define sipName_symbol &sipStrings_QtMultimediaWidgets[1522]
#define sipNameNr_suffix 1529
#define sipName_suffix &sipStrings_QtMultimediaWidgets[1529]
#define sipNameNr_offset 1536
#define sipName_offset &sipStrings_QtMultimediaWidgets[1536]
#define sipNameNr_prefix 1543
#define sipName_prefix &sipStrings_QtMultimediaWidgets[1543]
#define sipNameNr_filter 1550
#define sipName_filter &sipStrings_QtMultimediaWidgets[1550]
#define sipNameNr_option 1557
#define sipName_option &sipStrings_QtMultimediaWidgets[1557]
#define sipNameNr_locale 1564
#define sipName_locale &sipStrings_QtMultimediaWidgets[1564]
#define sipNameNr_format 471
#define sipName_format &sipStrings_QtMultimediaWidgets[471]
#define sipNameNr_column 1571
#define sipName_column &sipStrings_QtMultimediaWidgets[1571]
#define sipNameNr_parent 1578
#define sipName_parent &sipStrings_QtMultimediaWidgets[1578]
#define sipNameNr_paint 1585
#define sipName_paint &sipStrings_QtMultimediaWidgets[1585]
#define sipNameNr_brush 1591
#define sipName_brush &sipStrings_QtMultimediaWidgets[1591]
#define sipNameNr_shape 1597
#define sipName_shape &sipStrings_QtMultimediaWidgets[1597]
#define sipNameNr_types 1603
#define sipName_types &sipStrings_QtMultimediaWidgets[1603]
#define sipNameNr_order 1609
#define sipName_order &sipStrings_QtMultimediaWidgets[1609]
#define sipNameNr_flags 1615
#define sipName_flags &sipStrings_QtMultimediaWidgets[1615]
#define sipNameNr_event 1621
#define sipName_event &sipStrings_QtMultimediaWidgets[1621]
#define sipNameNr_msecs 1627
#define sipName_msecs &sipStrings_QtMultimediaWidgets[1627]
#define sipNameNr_state 1633
#define sipName_state &sipStrings_QtMultimediaWidgets[1633]
#define sipNameNr_port 1639
#define sipName_port &sipStrings_QtMultimediaWidgets[1639]
#define sipNameNr_mode 1644
#define sipName_mode &sipStrings_QtMultimediaWidgets[1644]
#define sipNameNr_name 1649
#define sipName_name &sipStrings_QtMultimediaWidgets[1649]
#define sipNameNr_base 1654
#define sipName_base &sipStrings_QtMultimediaWidgets[1654]
#define sipNameNr_fill 1659
#define sipName_fill &sipStrings_QtMultimediaWidgets[1659]
#define sipNameNr_size 1664
#define sipName_size &sipStrings_QtMultimediaWidgets[1664]
#define sipNameNr_type 1669
#define sipName_type &sipStrings_QtMultimediaWidgets[1669]
#define sipNameNr_from 1674
#define sipName_from &sipStrings_QtMultimediaWidgets[1674]
#define sipNameNr_sort 1679
#define sipName_sort &sipStrings_QtMultimediaWidgets[1679]
#define sipNameNr_pen 1684
#define sipName_pen &sipStrings_QtMultimediaWidgets[1684]
#define sipNameNr_hue 1688
#define sipName_hue &sipStrings_QtMultimediaWidgets[1688]
#define sipNameNr_pid 1692
#define sipName_pid &sipStrings_QtMultimediaWidgets[1692]
#define sipNameNr_pos 1696
#define sipName_pos &sipStrings_QtMultimediaWidgets[1696]
#define sipNameNr_sw 1700
#define sipName_sw &sipStrings_QtMultimediaWidgets[1700]
#define sipNameNr_sh 1594
#define sipName_sh &sipStrings_QtMultimediaWidgets[1594]
#define sipNameNr_sy 1703
#define sipName_sy &sipStrings_QtMultimediaWidgets[1703]
#define sipNameNr_sx 1706
#define sipName_sx &sipStrings_QtMultimediaWidgets[1706]
#define sipNameNr_at 475
#define sipName_at &sipStrings_QtMultimediaWidgets[475]

#define sipMalloc                   sipAPI_QtMultimediaWidgets->api_malloc
#define sipFree                     sipAPI_QtMultimediaWidgets->api_free
#define sipBuildResult              sipAPI_QtMultimediaWidgets->api_build_result
#define sipCallMethod               sipAPI_QtMultimediaWidgets->api_call_method
#define sipCallProcedureMethod      sipAPI_QtMultimediaWidgets->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtMultimediaWidgets->api_call_error_handler
#define sipParseResultEx            sipAPI_QtMultimediaWidgets->api_parse_result_ex
#define sipParseResult              sipAPI_QtMultimediaWidgets->api_parse_result
#define sipParseArgs                sipAPI_QtMultimediaWidgets->api_parse_args
#define sipParseKwdArgs             sipAPI_QtMultimediaWidgets->api_parse_kwd_args
#define sipParsePair                sipAPI_QtMultimediaWidgets->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtMultimediaWidgets->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtMultimediaWidgets->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtMultimediaWidgets->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_QtMultimediaWidgets->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_QtMultimediaWidgets->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtMultimediaWidgets->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtMultimediaWidgets->api_add_exception
#define sipNoFunction               sipAPI_QtMultimediaWidgets->api_no_function
#define sipNoMethod                 sipAPI_QtMultimediaWidgets->api_no_method
#define sipAbstractMethod           sipAPI_QtMultimediaWidgets->api_abstract_method
#define sipBadClass                 sipAPI_QtMultimediaWidgets->api_bad_class
#define sipBadCatcherResult         sipAPI_QtMultimediaWidgets->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtMultimediaWidgets->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtMultimediaWidgets->api_bad_operator_arg
#define sipTrace                    sipAPI_QtMultimediaWidgets->api_trace
#define sipTransferBack             sipAPI_QtMultimediaWidgets->api_transfer_back
#define sipTransferTo               sipAPI_QtMultimediaWidgets->api_transfer_to
#define sipTransferBreak            sipAPI_QtMultimediaWidgets->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtMultimediaWidgets->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtMultimediaWidgets->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtMultimediaWidgets->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtMultimediaWidgets->api_voidptr_type
#define sipGetPyObject              sipAPI_QtMultimediaWidgets->api_get_pyobject
#define sipGetAddress               sipAPI_QtMultimediaWidgets->api_get_address
#define sipGetMixinAddress          sipAPI_QtMultimediaWidgets->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtMultimediaWidgets->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtMultimediaWidgets->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtMultimediaWidgets->api_is_py_method
#define sipCallHook                 sipAPI_QtMultimediaWidgets->api_call_hook
#define sipEndThread                sipAPI_QtMultimediaWidgets->api_end_thread
#define sipConnectRx                sipAPI_QtMultimediaWidgets->api_connect_rx
#define sipDisconnectRx             sipAPI_QtMultimediaWidgets->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtMultimediaWidgets->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtMultimediaWidgets->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtMultimediaWidgets->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtMultimediaWidgets->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtMultimediaWidgets->api_free_sipslot
#define sipSameSlot                 sipAPI_QtMultimediaWidgets->api_same_slot
#define sipPySlotExtend             sipAPI_QtMultimediaWidgets->api_pyslot_extend
#define sipConvertRx                sipAPI_QtMultimediaWidgets->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtMultimediaWidgets->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtMultimediaWidgets->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtMultimediaWidgets->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtMultimediaWidgets->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtMultimediaWidgets->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtMultimediaWidgets->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtMultimediaWidgets->api_convert_to_bool
#define sipReleaseType              sipAPI_QtMultimediaWidgets->api_release_type
#define sipConvertFromType          sipAPI_QtMultimediaWidgets->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtMultimediaWidgets->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtMultimediaWidgets->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtMultimediaWidgets->api_convert_from_enum
#define sipGetState                 sipAPI_QtMultimediaWidgets->api_get_state
#define sipExportSymbol             sipAPI_QtMultimediaWidgets->api_export_symbol
#define sipImportSymbol             sipAPI_QtMultimediaWidgets->api_import_symbol
#define sipFindType                 sipAPI_QtMultimediaWidgets->api_find_type
#define sipFindNamedEnum            sipAPI_QtMultimediaWidgets->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtMultimediaWidgets->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtMultimediaWidgets->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtMultimediaWidgets->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtMultimediaWidgets->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtMultimediaWidgets->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtMultimediaWidgets->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtMultimediaWidgets->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtMultimediaWidgets->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtMultimediaWidgets->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtMultimediaWidgets->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtMultimediaWidgets->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtMultimediaWidgets->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtMultimediaWidgets->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtMultimediaWidgets->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtMultimediaWidgets->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtMultimediaWidgets->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtMultimediaWidgets->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtMultimediaWidgets->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtMultimediaWidgets->api_deprecated
#define sipGetReference             sipAPI_QtMultimediaWidgets->api_get_reference
#define sipKeepReference            sipAPI_QtMultimediaWidgets->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtMultimediaWidgets->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtMultimediaWidgets->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtMultimediaWidgets->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtMultimediaWidgets->api_type_scope
#define sipResolveTypedef           sipAPI_QtMultimediaWidgets->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtMultimediaWidgets->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtMultimediaWidgets->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtMultimediaWidgets->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtMultimediaWidgets->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtMultimediaWidgets->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtMultimediaWidgets->api_init_mixin
#define sipExportModule             sipAPI_QtMultimediaWidgets->api_export_module
#define sipInitModule               sipAPI_QtMultimediaWidgets->api_init_module
#define sipGetInterpreter           sipAPI_QtMultimediaWidgets->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtMultimediaWidgets->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtMultimediaWidgets->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtMultimediaWidgets->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtMultimediaWidgets->api_py_type_dict
#define sipPyTypeName               sipAPI_QtMultimediaWidgets->api_py_type_name
#define sipGetCFunction             sipAPI_QtMultimediaWidgets->api_get_c_function
#define sipGetMethod                sipAPI_QtMultimediaWidgets->api_get_method
#define sipFromMethod               sipAPI_QtMultimediaWidgets->api_from_method
#define sipGetDate                  sipAPI_QtMultimediaWidgets->api_get_date
#define sipFromDate                 sipAPI_QtMultimediaWidgets->api_from_date
#define sipGetDateTime              sipAPI_QtMultimediaWidgets->api_get_datetime
#define sipFromDateTime             sipAPI_QtMultimediaWidgets->api_from_datetime
#define sipGetTime                  sipAPI_QtMultimediaWidgets->api_get_time
#define sipFromTime                 sipAPI_QtMultimediaWidgets->api_from_time
#define sipIsUserType               sipAPI_QtMultimediaWidgets->api_is_user_type
#define sipGetFrame                 sipAPI_QtMultimediaWidgets->api_get_frame
#define sipCheckPluginForType       sipAPI_QtMultimediaWidgets->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtMultimediaWidgets->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtMultimediaWidgets->api_unicode_write
#define sipUnicodeData              sipAPI_QtMultimediaWidgets->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtMultimediaWidgets->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtMultimediaWidgets->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtMultimediaWidgets->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtMultimediaWidgets->api_is_derived_class
#define sipGetUserObject            sipAPI_QtMultimediaWidgets->api_get_user_object
#define sipSetUserObject            sipAPI_QtMultimediaWidgets->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtMultimediaWidgets->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtMultimediaWidgets->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtMultimediaWidgets->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtMultimediaWidgets->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtMultimediaWidgets->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtMultimediaWidgets->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtMultimediaWidgets->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtMultimediaWidgets->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtMultimediaWidgets->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtMultimediaWidgets->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtMultimediaWidgets->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtMultimediaWidgets->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtMultimediaWidgets->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtMultimediaWidgets->api_map_int_to_class
#define sipFindClass                sipAPI_QtMultimediaWidgets->api_find_class
#define sipFindMappedType           sipAPI_QtMultimediaWidgets->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtMultimediaWidgets->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtMultimediaWidgets->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtMultimediaWidgets->api_enable_gc
#define sipPrintObject              sipAPI_QtMultimediaWidgets->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtMultimediaWidgets->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtMultimediaWidgets[];

#define sipType_QVideoWidget sipExportedTypes_QtMultimediaWidgets[2]
#define sipClass_QVideoWidget sipExportedTypes_QtMultimediaWidgets[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimediaWidgets_QVideoWidget;

#define sipType_QCameraViewfinder sipExportedTypes_QtMultimediaWidgets[0]
#define sipClass_QCameraViewfinder sipExportedTypes_QtMultimediaWidgets[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimediaWidgets_QCameraViewfinder;

#define sipType_QGraphicsVideoItem sipExportedTypes_QtMultimediaWidgets[1]
#define sipClass_QGraphicsVideoItem sipExportedTypes_QtMultimediaWidgets[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtMultimediaWidgets_QGraphicsVideoItem;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtMultimediaWidgets;
extern sipExportedModuleDef sipModuleAPI_QtMultimediaWidgets;
extern sipTypeDef *sipExportedTypes_QtMultimediaWidgets[];

#define sipType_Qt_ItemSelectionMode sipImportedTypes_QtMultimediaWidgets_QtCore[13].it_td
#define sipEnum_Qt_ItemSelectionMode sipImportedTypes_QtMultimediaWidgets_QtCore[13].it_td->u.td_py_type

#define sipType_Qt_InputMethodQuery sipImportedTypes_QtMultimediaWidgets_QtCore[12].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_QtMultimediaWidgets_QtCore[12].it_td->u.td_py_type

#define sipType_Qt_AspectRatioMode sipImportedTypes_QtMultimediaWidgets_QtCore[11].it_td
#define sipEnum_Qt_AspectRatioMode sipImportedTypes_QtMultimediaWidgets_QtCore[11].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_QtMultimediaWidgets_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_QtMultimediaWidgets_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_QtMultimediaWidgets_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_QtMultimediaWidgets_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtMultimediaWidgets_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_QtMultimediaWidgets_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtMultimediaWidgets_QtCore[9].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtMultimediaWidgets_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtMultimediaWidgets_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_QtMultimediaWidgets_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_QtMultimediaWidgets_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_QtMultimediaWidgets_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QPointF sipImportedTypes_QtMultimediaWidgets_QtCore[5].it_td
#define sipClass_QPointF sipImportedTypes_QtMultimediaWidgets_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QRectF sipImportedTypes_QtMultimediaWidgets_QtCore[6].it_td
#define sipClass_QRectF sipImportedTypes_QtMultimediaWidgets_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_QtMultimediaWidgets_QtCore[7].it_td
#define sipClass_QSize sipImportedTypes_QtMultimediaWidgets_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QSizeF sipImportedTypes_QtMultimediaWidgets_QtCore[8].it_td
#define sipClass_QSizeF sipImportedTypes_QtMultimediaWidgets_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_QtMultimediaWidgets_QtCore[10].it_td
#define sipClass_QVariant sipImportedTypes_QtMultimediaWidgets_QtCore[10].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtMultimediaWidgets_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_QtMultimediaWidgets_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_QtMultimediaWidgets_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtMultimediaWidgets_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_QtMultimediaWidgets_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_QtMultimediaWidgets_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_QtMultimediaWidgets_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_QtMultimediaWidgets_QtGui[22].it_td
#define sipClass_QWheelEvent sipImportedTypes_QtMultimediaWidgets_QtGui[22].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_QtMultimediaWidgets_QtGui[21].it_td
#define sipClass_QTabletEvent sipImportedTypes_QtMultimediaWidgets_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_QtMultimediaWidgets_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_QtMultimediaWidgets_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_QtMultimediaWidgets_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_QtMultimediaWidgets_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_QtMultimediaWidgets_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_QtMultimediaWidgets_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_QtMultimediaWidgets_QtGui[19].it_td
#define sipClass_QResizeEvent sipImportedTypes_QtMultimediaWidgets_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_QtMultimediaWidgets_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_QtMultimediaWidgets_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_QtMultimediaWidgets_QtGui[20].it_td
#define sipClass_QShowEvent sipImportedTypes_QtMultimediaWidgets_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_QtMultimediaWidgets_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_QtMultimediaWidgets_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_QtMultimediaWidgets_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_QtMultimediaWidgets_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_QtMultimediaWidgets_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_QtMultimediaWidgets_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_QtMultimediaWidgets_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_QtMultimediaWidgets_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_QtMultimediaWidgets_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_QtMultimediaWidgets_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_QtMultimediaWidgets_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_QtMultimediaWidgets_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_QtMultimediaWidgets_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_QtMultimediaWidgets_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_QtMultimediaWidgets_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_QtMultimediaWidgets_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_QtMultimediaWidgets_QtGui[15].it_td->u.td_wrapper_type

#define sipType_QPainterPath sipImportedTypes_QtMultimediaWidgets_QtGui[18].it_td
#define sipClass_QPainterPath sipImportedTypes_QtMultimediaWidgets_QtGui[18].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtMultimediaWidgets_QtGui[];

#define sipType_QWidget sipImportedTypes_QtMultimediaWidgets_QtWidgets[9].it_td
#define sipClass_QWidget sipImportedTypes_QtMultimediaWidgets_QtWidgets[9].it_td->u.td_wrapper_type

#define sipType_QGraphicsItem sipImportedTypes_QtMultimediaWidgets_QtWidgets[0].it_td
#define sipClass_QGraphicsItem sipImportedTypes_QtMultimediaWidgets_QtWidgets[0].it_td->u.td_wrapper_type

#define sipType_QGraphicsItem_GraphicsItemChange sipImportedTypes_QtMultimediaWidgets_QtWidgets[1].it_td
#define sipEnum_QGraphicsItem_GraphicsItemChange sipImportedTypes_QtMultimediaWidgets_QtWidgets[1].it_td->u.td_py_type

#define sipType_QGraphicsObject sipImportedTypes_QtMultimediaWidgets_QtWidgets[2].it_td
#define sipClass_QGraphicsObject sipImportedTypes_QtMultimediaWidgets_QtWidgets[2].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneMouseEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[6].it_td
#define sipClass_QGraphicsSceneMouseEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[6].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneWheelEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[7].it_td
#define sipClass_QGraphicsSceneWheelEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[7].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneContextMenuEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[3].it_td
#define sipClass_QGraphicsSceneContextMenuEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[3].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneHoverEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[5].it_td
#define sipClass_QGraphicsSceneHoverEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[5].it_td->u.td_wrapper_type

#define sipType_QGraphicsSceneDragDropEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[4].it_td
#define sipClass_QGraphicsSceneDragDropEvent sipImportedTypes_QtMultimediaWidgets_QtWidgets[4].it_td->u.td_wrapper_type

#define sipType_QStyleOptionGraphicsItem sipImportedTypes_QtMultimediaWidgets_QtWidgets[8].it_td
#define sipClass_QStyleOptionGraphicsItem sipImportedTypes_QtMultimediaWidgets_QtWidgets[8].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtMultimediaWidgets_QtWidgets[];

#define sipType_QMediaObject sipImportedTypes_QtMultimediaWidgets_QtMultimedia[1].it_td
#define sipClass_QMediaObject sipImportedTypes_QtMultimediaWidgets_QtMultimedia[1].it_td->u.td_wrapper_type

#define sipType_QMediaBindableInterface sipImportedTypes_QtMultimediaWidgets_QtMultimedia[0].it_td
#define sipClass_QMediaBindableInterface sipImportedTypes_QtMultimediaWidgets_QtMultimedia[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_QtMultimediaWidgets_QtMultimedia[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtMultimediaWidgets_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtMultimediaWidgets_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_QtMultimediaWidgets_qt_metacast;
#line 73 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtMultimediaWidgets/qgraphicsvideoitem.sip"
// This is needed by the %ConvertToSubClassCode.
#include <QGraphicsVideoItem>
#line 744 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipAPIQtMultimediaWidgets.h"

#endif
