/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtMultimediaWidgets.h"

#line 26 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtMultimediaWidgets/qvideowidget.sip"
#include <qvideowidget.h>
#line 29 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"

#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 33 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtMultimedia/qmediaobject.sip"
#include <qmediaobject.h>
#line 36 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 386 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 39 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 400 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 42 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 413 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 45 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 459 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 48 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 448 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 51 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 54 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 57 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 60 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 63 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 66 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 69 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 30 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 72 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 75 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 78 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 81 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 84 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 87 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 90 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 93 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 96 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 99 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 189 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 102 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 105 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 108 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 111 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 114 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 117 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 120 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 123 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 126 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 129 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 497 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 132 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 558 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 135 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 607 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 138 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 580 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 141 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 596 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 144 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 663 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 147 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 293 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 150 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 470 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 153 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 426 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 372 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 159 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 351 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 162 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 253 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 165 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 205 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 168 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 52 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 171 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 149 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 174 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 177 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 180 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 183 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 186 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 189 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 192 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 195 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 198 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 201 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 204 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 247 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 207 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 235 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 210 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 213 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 38 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 216 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 149 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 219 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 222 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 225 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 228 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 231 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 234 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtMultimediaWidgets/sipQtMultimediaWidgetsQVideoWidget.cpp"


class sipQVideoWidget : public  ::QVideoWidget
{
public:
    sipQVideoWidget( ::QWidget*);
    virtual ~sipQVideoWidget();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
     ::QMediaObject* mediaObject() const;
    bool setMediaObject( ::QMediaObject*);
    void disconnectNotify(const  ::QMetaMethod&);
    void connectNotify(const  ::QMetaMethod&);
    void customEvent( ::QEvent*);
    void childEvent( ::QChildEvent*);
    void timerEvent( ::QTimerEvent*);
    bool eventFilter( ::QObject*, ::QEvent*);
    bool event( ::QEvent*);
    int metric( ::QPaintDevice::PaintDeviceMetric) const;
     ::QPaintEngine* paintEngine() const;
    int devType() const;
    void setVisible(bool);
     ::QSize sizeHint() const;
     ::QSize minimumSizeHint() const;
    int heightForWidth(int) const;
    void mousePressEvent( ::QMouseEvent*);
    void mouseReleaseEvent( ::QMouseEvent*);
    void mouseDoubleClickEvent( ::QMouseEvent*);
    void mouseMoveEvent( ::QMouseEvent*);
    void wheelEvent( ::QWheelEvent*);
    void keyPressEvent( ::QKeyEvent*);
    void keyReleaseEvent( ::QKeyEvent*);
    void focusInEvent( ::QFocusEvent*);
    void focusOutEvent( ::QFocusEvent*);
    void enterEvent( ::QEvent*);
    void leaveEvent( ::QEvent*);
    void paintEvent( ::QPaintEvent*);
    void moveEvent( ::QMoveEvent*);
    void resizeEvent( ::QResizeEvent*);
    void closeEvent( ::QCloseEvent*);
    void contextMenuEvent( ::QContextMenuEvent*);
    void tabletEvent( ::QTabletEvent*);
    void actionEvent( ::QActionEvent*);
    void dragEnterEvent( ::QDragEnterEvent*);
    void dragMoveEvent( ::QDragMoveEvent*);
    void dragLeaveEvent( ::QDragLeaveEvent*);
    void dropEvent( ::QDropEvent*);
    void showEvent( ::QShowEvent*);
    void hideEvent( ::QHideEvent*);
    void changeEvent( ::QEvent*);
    void inputMethodEvent( ::QInputMethodEvent*);
     ::QVariant inputMethodQuery( ::Qt::InputMethodQuery) const;
    bool focusNextPrevChild(bool);
    bool hasHeightForWidth() const;
    bool nativeEvent(const  ::QByteArray&,void*,long*);
     ::QPainter* sharedPainter() const;
    void initPainter( ::QPainter*) const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQVideoWidget(const sipQVideoWidget &);
    sipQVideoWidget &operator = (const sipQVideoWidget &);

    char sipPyMethods[48];
};

sipQVideoWidget::sipQVideoWidget( ::QWidget*a0):  ::QVideoWidget(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQVideoWidget::~sipQVideoWidget()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

const QMetaObject *sipQVideoWidget::metaObject() const
{
    if (sipGetInterpreter())
        return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtMultimediaWidgets_qt_metaobject(sipPySelf,sipType_QVideoWidget);

    return  ::QVideoWidget::metaObject();
}

int sipQVideoWidget::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id =  ::QVideoWidget::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtMultimediaWidgets_qt_metacall(sipPySelf,sipType_QVideoWidget,_c,_id,_a);

    return _id;
}

void *sipQVideoWidget::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtMultimediaWidgets_qt_metacast(sipPySelf, sipType_QVideoWidget, _clname, &sipCpp) ? sipCpp :  ::QVideoWidget::qt_metacast(_clname));
}

 ::QMediaObject* sipQVideoWidget::mediaObject() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_mediaObject);

    if (!sipMeth)
        return  ::QVideoWidget::mediaObject();

    extern  ::QMediaObject* sipVH_QtMultimediaWidgets_37(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_37(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

bool sipQVideoWidget::setMediaObject( ::QMediaObject*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_setMediaObject);

    if (!sipMeth)
        return  ::QVideoWidget::setMediaObject(a0);

    extern bool sipVH_QtMultimediaWidgets_36(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMediaObject*);

    return sipVH_QtMultimediaWidgets_36(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::disconnectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
         ::QVideoWidget::disconnectNotify(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_35(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtMultimediaWidgets_35(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::connectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
         ::QVideoWidget::connectNotify(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_35(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtMultimediaWidgets_35(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::customEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::customEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtMultimediaWidgets_7(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::childEvent( ::QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::childEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_34(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QChildEvent*);

    sipVH_QtMultimediaWidgets_34(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::timerEvent( ::QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::timerEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_33(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTimerEvent*);

    sipVH_QtMultimediaWidgets_33(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQVideoWidget::eventFilter( ::QObject*a0, ::QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return  ::QVideoWidget::eventFilter(a0,a1);

    extern bool sipVH_QtMultimediaWidgets_32(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*, ::QEvent*);

    return sipVH_QtMultimediaWidgets_32(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

bool sipQVideoWidget::event( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return  ::QVideoWidget::event(a0);

    extern bool sipVH_QtMultimediaWidgets_31(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    return sipVH_QtMultimediaWidgets_31(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

int sipQVideoWidget::metric( ::QPaintDevice::PaintDeviceMetric a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,NULL,sipName_metric);

    if (!sipMeth)
        return  ::QVideoWidget::metric(a0);

    extern int sipVH_QtMultimediaWidgets_30(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QPaintDevice::PaintDeviceMetric);

    return sipVH_QtMultimediaWidgets_30(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::QPaintEngine* sipQVideoWidget::paintEngine() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,NULL,sipName_paintEngine);

    if (!sipMeth)
        return  ::QVideoWidget::paintEngine();

    extern  ::QPaintEngine* sipVH_QtMultimediaWidgets_29(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_29(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

int sipQVideoWidget::devType() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,NULL,sipName_devType);

    if (!sipMeth)
        return  ::QVideoWidget::devType();

    extern int sipVH_QtMultimediaWidgets_28(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_28(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

void sipQVideoWidget::setVisible(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_setVisible);

    if (!sipMeth)
    {
         ::QVideoWidget::setVisible(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_27(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    sipVH_QtMultimediaWidgets_27(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::QSize sipQVideoWidget::sizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[13]),sipPySelf,NULL,sipName_sizeHint);

    if (!sipMeth)
        return  ::QVideoWidget::sizeHint();

    extern  ::QSize sipVH_QtMultimediaWidgets_26(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_26(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

 ::QSize sipQVideoWidget::minimumSizeHint() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[14]),sipPySelf,NULL,sipName_minimumSizeHint);

    if (!sipMeth)
        return  ::QVideoWidget::minimumSizeHint();

    extern  ::QSize sipVH_QtMultimediaWidgets_26(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_26(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

int sipQVideoWidget::heightForWidth(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[15]),sipPySelf,NULL,sipName_heightForWidth);

    if (!sipMeth)
        return  ::QVideoWidget::heightForWidth(a0);

    extern int sipVH_QtMultimediaWidgets_25(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_QtMultimediaWidgets_25(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::mousePressEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_mousePressEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::mousePressEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtMultimediaWidgets_24(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::mouseReleaseEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_mouseReleaseEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::mouseReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtMultimediaWidgets_24(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::mouseDoubleClickEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_mouseDoubleClickEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::mouseDoubleClickEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtMultimediaWidgets_24(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::mouseMoveEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_mouseMoveEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::mouseMoveEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_24(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtMultimediaWidgets_24(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::wheelEvent( ::QWheelEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_wheelEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::wheelEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_23(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QWheelEvent*);

    sipVH_QtMultimediaWidgets_23(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::keyPressEvent( ::QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_keyPressEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::keyPressEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_22(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QKeyEvent*);

    sipVH_QtMultimediaWidgets_22(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::keyReleaseEvent( ::QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_keyReleaseEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::keyReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_22(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QKeyEvent*);

    sipVH_QtMultimediaWidgets_22(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::focusInEvent( ::QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_focusInEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::focusInEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_21(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QFocusEvent*);

    sipVH_QtMultimediaWidgets_21(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::focusOutEvent( ::QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_focusOutEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::focusOutEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_21(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QFocusEvent*);

    sipVH_QtMultimediaWidgets_21(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::enterEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_enterEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::enterEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtMultimediaWidgets_7(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::leaveEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_leaveEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::leaveEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtMultimediaWidgets_7(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::paintEvent( ::QPaintEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_paintEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::paintEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QPaintEvent*);

    sipVH_QtMultimediaWidgets_20(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::moveEvent( ::QMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_moveEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::moveEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_19(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMoveEvent*);

    sipVH_QtMultimediaWidgets_19(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::resizeEvent( ::QResizeEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_resizeEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::resizeEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_18(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QResizeEvent*);

    sipVH_QtMultimediaWidgets_18(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::closeEvent( ::QCloseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_closeEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::closeEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_17(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QCloseEvent*);

    sipVH_QtMultimediaWidgets_17(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::contextMenuEvent( ::QContextMenuEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_contextMenuEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::contextMenuEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_16(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QContextMenuEvent*);

    sipVH_QtMultimediaWidgets_16(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::tabletEvent( ::QTabletEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[32],sipPySelf,NULL,sipName_tabletEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::tabletEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_15(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTabletEvent*);

    sipVH_QtMultimediaWidgets_15(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::actionEvent( ::QActionEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[33],sipPySelf,NULL,sipName_actionEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::actionEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_14(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QActionEvent*);

    sipVH_QtMultimediaWidgets_14(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::dragEnterEvent( ::QDragEnterEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[34],sipPySelf,NULL,sipName_dragEnterEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::dragEnterEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_13(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QDragEnterEvent*);

    sipVH_QtMultimediaWidgets_13(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::dragMoveEvent( ::QDragMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[35],sipPySelf,NULL,sipName_dragMoveEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::dragMoveEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QDragMoveEvent*);

    sipVH_QtMultimediaWidgets_12(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::dragLeaveEvent( ::QDragLeaveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[36],sipPySelf,NULL,sipName_dragLeaveEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::dragLeaveEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QDragLeaveEvent*);

    sipVH_QtMultimediaWidgets_11(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::dropEvent( ::QDropEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[37],sipPySelf,NULL,sipName_dropEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::dropEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_10(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QDropEvent*);

    sipVH_QtMultimediaWidgets_10(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::showEvent( ::QShowEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[38],sipPySelf,NULL,sipName_showEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::showEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_9(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QShowEvent*);

    sipVH_QtMultimediaWidgets_9(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::hideEvent( ::QHideEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[39],sipPySelf,NULL,sipName_hideEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::hideEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_8(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QHideEvent*);

    sipVH_QtMultimediaWidgets_8(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::changeEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[40],sipPySelf,NULL,sipName_changeEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::changeEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtMultimediaWidgets_7(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQVideoWidget::inputMethodEvent( ::QInputMethodEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[41],sipPySelf,NULL,sipName_inputMethodEvent);

    if (!sipMeth)
    {
         ::QVideoWidget::inputMethodEvent(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QInputMethodEvent*);

    sipVH_QtMultimediaWidgets_6(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::QVariant sipQVideoWidget::inputMethodQuery( ::Qt::InputMethodQuery a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[42]),sipPySelf,NULL,sipName_inputMethodQuery);

    if (!sipMeth)
        return  ::QVideoWidget::inputMethodQuery(a0);

    extern  ::QVariant sipVH_QtMultimediaWidgets_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::Qt::InputMethodQuery);

    return sipVH_QtMultimediaWidgets_5(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQVideoWidget::focusNextPrevChild(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[43],sipPySelf,NULL,sipName_focusNextPrevChild);

    if (!sipMeth)
        return  ::QVideoWidget::focusNextPrevChild(a0);

    extern bool sipVH_QtMultimediaWidgets_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, bool);

    return sipVH_QtMultimediaWidgets_4(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQVideoWidget::hasHeightForWidth() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[44]),sipPySelf,NULL,sipName_hasHeightForWidth);

    if (!sipMeth)
        return  ::QVideoWidget::hasHeightForWidth();

    extern bool sipVH_QtMultimediaWidgets_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_3(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

bool sipQVideoWidget::nativeEvent(const  ::QByteArray& a0,void*a1,long*a2)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[45],sipPySelf,NULL,sipName_nativeEvent);

    if (!sipMeth)
        return  ::QVideoWidget::nativeEvent(a0,a1,a2);

    extern bool sipVH_QtMultimediaWidgets_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QByteArray&,void*,long*);

    return sipVH_QtMultimediaWidgets_2(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1, a2);
}

 ::QPainter* sipQVideoWidget::sharedPainter() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[46]),sipPySelf,NULL,sipName_sharedPainter);

    if (!sipMeth)
        return  ::QVideoWidget::sharedPainter();

    extern  ::QPainter* sipVH_QtMultimediaWidgets_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtMultimediaWidgets_1(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

void sipQVideoWidget::initPainter( ::QPainter*a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[47]),sipPySelf,NULL,sipName_initPainter);

    if (!sipMeth)
    {
         ::QVideoWidget::initPainter(a0);
        return;
    }

    extern void sipVH_QtMultimediaWidgets_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QPainter*);

    sipVH_QtMultimediaWidgets_0(sipGILState, sipImportedVirtErrorHandlers_QtMultimediaWidgets_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QVideoWidget_mediaObject, "mediaObject(self) -> QMediaObject");

extern "C" {static PyObject *meth_QVideoWidget_mediaObject(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_mediaObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
             ::QMediaObject*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp-> ::QVideoWidget::mediaObject() : sipCpp->mediaObject());

            return sipConvertFromType(sipRes,sipType_QMediaObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_mediaObject, doc_QVideoWidget_mediaObject);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_aspectRatioMode, "aspectRatioMode(self) -> Qt.AspectRatioMode");

extern "C" {static PyObject *meth_QVideoWidget_aspectRatioMode(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_aspectRatioMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
             ::Qt::AspectRatioMode sipRes;

            sipRes = sipCpp->aspectRatioMode();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_Qt_AspectRatioMode);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_aspectRatioMode, doc_QVideoWidget_aspectRatioMode);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_brightness, "brightness(self) -> int");

extern "C" {static PyObject *meth_QVideoWidget_brightness(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_brightness(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->brightness();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_brightness, doc_QVideoWidget_brightness);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_contrast, "contrast(self) -> int");

extern "C" {static PyObject *meth_QVideoWidget_contrast(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_contrast(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->contrast();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_contrast, doc_QVideoWidget_contrast);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_hue, "hue(self) -> int");

extern "C" {static PyObject *meth_QVideoWidget_hue(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_hue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->hue();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_hue, doc_QVideoWidget_hue);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_saturation, "saturation(self) -> int");

extern "C" {static PyObject *meth_QVideoWidget_saturation(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_saturation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->saturation();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_saturation, doc_QVideoWidget_saturation);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_sizeHint, "sizeHint(self) -> QSize");

extern "C" {static PyObject *meth_QVideoWidget_sizeHint(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_sizeHint(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
        const  ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QVideoWidget, &sipCpp))
        {
             ::QSize*sipRes;

            sipRes = new  ::QSize((sipSelfWasArg ? sipCpp-> ::QVideoWidget::sizeHint() : sipCpp->sizeHint()));

            return sipConvertFromNewType(sipRes,sipType_QSize,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_sizeHint, doc_QVideoWidget_sizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setFullScreen, "setFullScreen(self, bool)");

extern "C" {static PyObject *meth_QVideoWidget_setFullScreen(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setFullScreen(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QVideoWidget, &sipCpp, &a0))
        {
            sipCpp->setFullScreen(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setFullScreen, doc_QVideoWidget_setFullScreen);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setAspectRatioMode, "setAspectRatioMode(self, Qt.AspectRatioMode)");

extern "C" {static PyObject *meth_QVideoWidget_setAspectRatioMode(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setAspectRatioMode(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::Qt::AspectRatioMode a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_Qt_AspectRatioMode, &a0))
        {
            sipCpp->setAspectRatioMode(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setAspectRatioMode, doc_QVideoWidget_setAspectRatioMode);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setBrightness, "setBrightness(self, int)");

extern "C" {static PyObject *meth_QVideoWidget_setBrightness(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setBrightness(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QVideoWidget, &sipCpp, &a0))
        {
            sipCpp->setBrightness(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setBrightness, doc_QVideoWidget_setBrightness);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setContrast, "setContrast(self, int)");

extern "C" {static PyObject *meth_QVideoWidget_setContrast(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setContrast(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QVideoWidget, &sipCpp, &a0))
        {
            sipCpp->setContrast(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setContrast, doc_QVideoWidget_setContrast);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setHue, "setHue(self, int)");

extern "C" {static PyObject *meth_QVideoWidget_setHue(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setHue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QVideoWidget, &sipCpp, &a0))
        {
            sipCpp->setHue(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setHue, doc_QVideoWidget_setHue);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setSaturation, "setSaturation(self, int)");

extern "C" {static PyObject *meth_QVideoWidget_setSaturation(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setSaturation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QVideoWidget, &sipCpp, &a0))
        {
            sipCpp->setSaturation(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setSaturation, doc_QVideoWidget_setSaturation);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_event, "event(self, QEvent) -> bool");

extern "C" {static PyObject *meth_QVideoWidget_event(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_event(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QEvent, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp-> ::QVideoWidget::event(a0) : sipCpp->event(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_event, doc_QVideoWidget_event);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_showEvent, "showEvent(self, QShowEvent)");

extern "C" {static PyObject *meth_QVideoWidget_showEvent(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_showEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QShowEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QShowEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::QVideoWidget::showEvent(a0) : sipCpp->showEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_showEvent, doc_QVideoWidget_showEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_hideEvent, "hideEvent(self, QHideEvent)");

extern "C" {static PyObject *meth_QVideoWidget_hideEvent(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_hideEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QHideEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QHideEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::QVideoWidget::hideEvent(a0) : sipCpp->hideEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_hideEvent, doc_QVideoWidget_hideEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_resizeEvent, "resizeEvent(self, QResizeEvent)");

extern "C" {static PyObject *meth_QVideoWidget_resizeEvent(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_resizeEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QResizeEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QResizeEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::QVideoWidget::resizeEvent(a0) : sipCpp->resizeEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_resizeEvent, doc_QVideoWidget_resizeEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_moveEvent, "moveEvent(self, QMoveEvent)");

extern "C" {static PyObject *meth_QVideoWidget_moveEvent(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_moveEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QMoveEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QMoveEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::QVideoWidget::moveEvent(a0) : sipCpp->moveEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_moveEvent, doc_QVideoWidget_moveEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_paintEvent, "paintEvent(self, QPaintEvent)");

extern "C" {static PyObject *meth_QVideoWidget_paintEvent(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_paintEvent(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QPaintEvent* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QPaintEvent, &a0))
        {
            (sipSelfWasArg ? sipCpp-> ::QVideoWidget::paintEvent(a0) : sipCpp->paintEvent(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_paintEvent, doc_QVideoWidget_paintEvent);

    return NULL;
}


PyDoc_STRVAR(doc_QVideoWidget_setMediaObject, "setMediaObject(self, QMediaObject) -> bool");

extern "C" {static PyObject *meth_QVideoWidget_setMediaObject(PyObject *, PyObject *);}
static PyObject *meth_QVideoWidget_setMediaObject(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerivedClass((sipSimpleWrapper *)sipSelf));

    {
         ::QMediaObject* a0;
         ::QVideoWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ8", &sipSelf, sipType_QVideoWidget, &sipCpp, sipType_QMediaObject, &a0))
        {
            bool sipRes;

            sipRes = (sipSelfWasArg ? sipCpp-> ::QVideoWidget::setMediaObject(a0) : sipCpp->setMediaObject(a0));

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QVideoWidget, sipName_setMediaObject, doc_QVideoWidget_setMediaObject);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QVideoWidget(void *, const sipTypeDef *);}
static void *cast_QVideoWidget(void *sipCppV, const sipTypeDef *targetType)
{
     ::QVideoWidget *sipCpp = reinterpret_cast< ::QVideoWidget *>(sipCppV);

    if (targetType == sipType_QWidget)
        return static_cast< ::QWidget *>(sipCpp);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    if (targetType == sipType_QPaintDevice)
        return static_cast< ::QPaintDevice *>(sipCpp);

    if (targetType == sipType_QMediaBindableInterface)
        return static_cast< ::QMediaBindableInterface *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QVideoWidget(void *, int);}
static void release_QVideoWidget(void *sipCppV, int)
{
     ::QVideoWidget *sipCpp = reinterpret_cast< ::QVideoWidget *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QVideoWidget(sipSimpleWrapper *);}
static void dealloc_QVideoWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQVideoWidget *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QVideoWidget(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QVideoWidget(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QVideoWidget(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQVideoWidget *sipCpp = 0;

    {
         ::QWidget* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QWidget, &a0, sipOwner))
        {
            sipCpp = new sipQVideoWidget(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QVideoWidget[] = {{9, 2, 0}, {0, 4, 1}};


static PyMethodDef methods_QVideoWidget[] = {
    {SIP_MLNAME_CAST(sipName_aspectRatioMode), meth_QVideoWidget_aspectRatioMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_aspectRatioMode)},
    {SIP_MLNAME_CAST(sipName_brightness), meth_QVideoWidget_brightness, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_brightness)},
    {SIP_MLNAME_CAST(sipName_contrast), meth_QVideoWidget_contrast, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_contrast)},
    {SIP_MLNAME_CAST(sipName_event), meth_QVideoWidget_event, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_event)},
    {SIP_MLNAME_CAST(sipName_hideEvent), meth_QVideoWidget_hideEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_hideEvent)},
    {SIP_MLNAME_CAST(sipName_hue), meth_QVideoWidget_hue, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_hue)},
    {SIP_MLNAME_CAST(sipName_mediaObject), meth_QVideoWidget_mediaObject, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_mediaObject)},
    {SIP_MLNAME_CAST(sipName_moveEvent), meth_QVideoWidget_moveEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_moveEvent)},
    {SIP_MLNAME_CAST(sipName_paintEvent), meth_QVideoWidget_paintEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_paintEvent)},
    {SIP_MLNAME_CAST(sipName_resizeEvent), meth_QVideoWidget_resizeEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_resizeEvent)},
    {SIP_MLNAME_CAST(sipName_saturation), meth_QVideoWidget_saturation, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_saturation)},
    {SIP_MLNAME_CAST(sipName_setAspectRatioMode), meth_QVideoWidget_setAspectRatioMode, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setAspectRatioMode)},
    {SIP_MLNAME_CAST(sipName_setBrightness), meth_QVideoWidget_setBrightness, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setBrightness)},
    {SIP_MLNAME_CAST(sipName_setContrast), meth_QVideoWidget_setContrast, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setContrast)},
    {SIP_MLNAME_CAST(sipName_setFullScreen), meth_QVideoWidget_setFullScreen, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setFullScreen)},
    {SIP_MLNAME_CAST(sipName_setHue), meth_QVideoWidget_setHue, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setHue)},
    {SIP_MLNAME_CAST(sipName_setMediaObject), meth_QVideoWidget_setMediaObject, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setMediaObject)},
    {SIP_MLNAME_CAST(sipName_setSaturation), meth_QVideoWidget_setSaturation, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_setSaturation)},
    {SIP_MLNAME_CAST(sipName_showEvent), meth_QVideoWidget_showEvent, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_showEvent)},
    {SIP_MLNAME_CAST(sipName_sizeHint), meth_QVideoWidget_sizeHint, METH_VARARGS, SIP_MLDOC_CAST(doc_QVideoWidget_sizeHint)}
};

PyDoc_STRVAR(doc_QVideoWidget, "\1QVideoWidget(parent: QWidget = None)");


/* Define this type's signals. */
static const pyqt5QtSignal signals_QVideoWidget[] = {
    {"saturationChanged(int)", "\1saturationChanged(self, int)", 0, 0},
    {"hueChanged(int)", "\1hueChanged(self, int)", 0, 0},
    {"contrastChanged(int)", "\1contrastChanged(self, int)", 0, 0},
    {"brightnessChanged(int)", "\1brightnessChanged(self, int)", 0, 0},
    {"fullScreenChanged(bool)", "\1fullScreenChanged(self, bool)", 0, 0},
    {0, 0, 0, 0}
};


static pyqt5ClassPluginDef plugin_QVideoWidget = {
    & ::QVideoWidget::staticMetaObject,
    0,
    signals_QVideoWidget,
    0
};


sipClassTypeDef sipTypeDef_QtMultimediaWidgets_QVideoWidget = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QVideoWidget,
        {0},
        &plugin_QVideoWidget
    },
    {
        sipNameNr_QVideoWidget,
        {0, 0, 1},
        20, methods_QVideoWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QVideoWidget,
    -1,
    -1,
    supers_QVideoWidget,
    0,
    init_type_QVideoWidget,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QVideoWidget,
    0,
    0,
    0,
    release_QVideoWidget,
    cast_QVideoWidget,
    0,
    0,
    0,
    0,
    0,
    0
};
