/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtDesigner.h"

#line 26 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtDesigner/abstractwidgetbox.sip"
#include <abstractwidgetbox.h>
#line 29 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"

#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 33 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 36 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 27 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 39 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 42 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 45 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 48 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 30 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 51 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qwindow.sip"
#include <qwindow.h>
#line 54 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qpixmap.sip"
#include <qpixmap.h>
#line 57 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 60 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 63 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 66 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 69 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 72 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 75 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 189 "sip/QtCore/qglobal.sip"
#include <QtGlobal>
#line 78 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 81 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 84 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 87 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 90 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 28 "sip/QtWidgets/qwidget.sip"
#include <qwidget.h>
#line 93 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 96 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 99 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 102 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 105 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 108 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 497 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 111 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 114 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 459 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 117 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 448 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 120 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 558 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 123 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 607 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 126 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 580 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 129 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 596 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 132 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 663 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 135 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 293 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 138 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 470 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 141 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 426 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 144 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 413 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 147 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 400 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 150 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 386 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 153 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 372 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 351 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 159 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 253 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 162 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 205 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 165 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 52 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 168 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 149 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 171 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qaction.sip"
#include <qaction.h>
#line 174 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qlayout.sip"
#include <qlayout.h>
#line 177 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 180 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 183 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 186 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 189 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 192 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 195 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtWidgets/qstyle.sip"
#include <qstyle.h>
#line 198 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 201 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 247 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 204 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 235 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 207 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 28 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 210 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 38 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 213 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 149 "sip/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 216 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 219 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 222 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 225 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 228 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 231 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtDesigner/sipQtDesignerQDesignerWidgetBoxInterface.cpp"


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_setFileName, "setFileName(self, str)");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_setFileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const  ::QString* a0;
        int a0State = 0;
         ::QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp, sipType_QString,&a0, &a0State))
        {
            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_setFileName);
                return NULL;
            }

            sipCpp->setFileName(*a0);
            sipReleaseType(const_cast< ::QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_setFileName, doc_QDesignerWidgetBoxInterface_setFileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_fileName, "fileName(self) -> str");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_fileName(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
        const  ::QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
             ::QString*sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_fileName);
                return NULL;
            }

            sipRes = new  ::QString(sipCpp->fileName());

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_fileName, doc_QDesignerWidgetBoxInterface_fileName);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_load, "load(self) -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_load(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
         ::QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_load);
                return NULL;
            }

            sipRes = sipCpp->load();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_load, doc_QDesignerWidgetBoxInterface_load);

    return NULL;
}


PyDoc_STRVAR(doc_QDesignerWidgetBoxInterface_save, "save(self) -> bool");

extern "C" {static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *, PyObject *);}
static PyObject *meth_QDesignerWidgetBoxInterface_save(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
         ::QDesignerWidgetBoxInterface *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDesignerWidgetBoxInterface, &sipCpp))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDesignerWidgetBoxInterface, sipName_save);
                return NULL;
            }

            sipRes = sipCpp->save();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDesignerWidgetBoxInterface, sipName_save, doc_QDesignerWidgetBoxInterface_save);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QDesignerWidgetBoxInterface(void *, const sipTypeDef *);}
static void *cast_QDesignerWidgetBoxInterface(void *sipCppV, const sipTypeDef *targetType)
{
     ::QDesignerWidgetBoxInterface *sipCpp = reinterpret_cast< ::QDesignerWidgetBoxInterface *>(sipCppV);

    if (targetType == sipType_QWidget)
        return static_cast< ::QWidget *>(sipCpp);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    if (targetType == sipType_QPaintDevice)
        return static_cast< ::QPaintDevice *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDesignerWidgetBoxInterface(void *, int);}
static void release_QDesignerWidgetBoxInterface(void *sipCppV, int)
{
     ::QDesignerWidgetBoxInterface *sipCpp = reinterpret_cast< ::QDesignerWidgetBoxInterface *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *);}
static void dealloc_QDesignerWidgetBoxInterface(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QDesignerWidgetBoxInterface(sipGetAddress(sipSelf), 0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDesignerWidgetBoxInterface[] = {{3, 2, 1}};


static PyMethodDef methods_QDesignerWidgetBoxInterface[] = {
    {SIP_MLNAME_CAST(sipName_fileName), meth_QDesignerWidgetBoxInterface_fileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_fileName)},
    {SIP_MLNAME_CAST(sipName_load), meth_QDesignerWidgetBoxInterface_load, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_load)},
    {SIP_MLNAME_CAST(sipName_save), meth_QDesignerWidgetBoxInterface_save, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_save)},
    {SIP_MLNAME_CAST(sipName_setFileName), meth_QDesignerWidgetBoxInterface_setFileName, METH_VARARGS, SIP_MLDOC_CAST(doc_QDesignerWidgetBoxInterface_setFileName)}
};


static pyqt5ClassPluginDef plugin_QDesignerWidgetBoxInterface = {
    & ::QDesignerWidgetBoxInterface::staticMetaObject,
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtDesigner_QDesignerWidgetBoxInterface = {
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QDesignerWidgetBoxInterface,
        {0},
        &plugin_QDesignerWidgetBoxInterface
    },
    {
        sipNameNr_QDesignerWidgetBoxInterface,
        {0, 0, 1},
        4, methods_QDesignerWidgetBoxInterface,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    release_QDesignerWidgetBoxInterface,
    cast_QDesignerWidgetBoxInterface,
    0,
    0,
    0,
    0,
    0,
    0
};
