/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#ifndef _QtPositioningAPI_H
#define _QtPositioningAPI_H

#if !defined(Py_LIMITED_API)
#define Py_LIMITED_API
#endif

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_MACX


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QGeoPositionInfoSource__PositioningMethods 0
#define sipName_QGeoPositionInfoSource__PositioningMethods &sipStrings_QtPositioning[0]
#define sipNameNr_QGeoAreaMonitorSource__AreaMonitorFeatures 43
#define sipName_QGeoAreaMonitorSource__AreaMonitorFeatures &sipStrings_QtPositioning[43]
#define sipNameNr_QGeoPositionInfoSource__PositioningMethod 86
#define sipName_QGeoPositionInfoSource__PositioningMethod &sipStrings_QtPositioning[86]
#define sipNameNr_QGeoAreaMonitorSource__AreaMonitorFeature 128
#define sipName_QGeoAreaMonitorSource__AreaMonitorFeature &sipStrings_QtPositioning[128]
#define sipNameNr_QNmeaPositionInfoSource__UpdateMode 170
#define sipName_QNmeaPositionInfoSource__UpdateMode &sipStrings_QtPositioning[170]
#define sipNameNr_fromSatellitePositioningMethodsOnly 206
#define sipName_fromSatellitePositioningMethodsOnly &sipStrings_QtPositioning[206]
#define sipNameNr_DegreesMinutesSecondsWithHemisphere 242
#define sipName_DegreesMinutesSecondsWithHemisphere &sipStrings_QtPositioning[242]
#define sipNameNr_QGeoSatelliteInfo__SatelliteSystem 278
#define sipName_QGeoSatelliteInfo__SatelliteSystem &sipStrings_QtPositioning[278]
#define sipNameNr_QGeoCoordinate__CoordinateFormat 313
#define sipName_QGeoCoordinate__CoordinateFormat &sipStrings_QtPositioning[313]
#define sipNameNr_QGeoSatelliteInfoSource__Error 346
#define sipName_QGeoSatelliteInfoSource__Error &sipStrings_QtPositioning[346]
#define sipNameNr_setPreferredPositioningMethods 377
#define sipName_setPreferredPositioningMethods &sipStrings_QtPositioning[377]
#define sipNameNr_NonSatellitePositioningMethods 408
#define sipName_NonSatellitePositioningMethods &sipStrings_QtPositioning[408]
#define sipNameNr_QGeoCoordinate__CoordinateType 439
#define sipName_QGeoCoordinate__CoordinateType &sipStrings_QtPositioning[439]
#define sipNameNr_QGeoPositionInfoSource__Error 470
#define sipName_QGeoPositionInfoSource__Error &sipStrings_QtPositioning[470]
#define sipNameNr_QGeoSatelliteInfo__Attribute 500
#define sipName_QGeoSatelliteInfo__Attribute &sipStrings_QtPositioning[500]
#define sipNameNr_DegreesMinutesWithHemisphere 529
#define sipName_DegreesMinutesWithHemisphere &sipStrings_QtPositioning[529]
#define sipNameNr_supportedAreaMonitorFeatures 558
#define sipName_supportedAreaMonitorFeatures &sipStrings_QtPositioning[558]
#define sipNameNr_PersistentAreaMonitorFeature 587
#define sipName_PersistentAreaMonitorFeature &sipStrings_QtPositioning[587]
#define sipNameNr_QGeoAreaMonitorSource__Error 616
#define sipName_QGeoAreaMonitorSource__Error &sipStrings_QtPositioning[616]
#define sipNameNr_setUserEquivalentRangeError 645
#define sipName_setUserEquivalentRangeError &sipStrings_QtPositioning[645]
#define sipNameNr_supportedPositioningMethods 673
#define sipName_supportedPositioningMethods &sipStrings_QtPositioning[673]
#define sipNameNr_preferredPositioningMethods 701
#define sipName_preferredPositioningMethods &sipStrings_QtPositioning[701]
#define sipNameNr_SatellitePositioningMethods 411
#define sipName_SatellitePositioningMethods &sipStrings_QtPositioning[411]
#define sipNameNr_QGeoPositionInfo__Attribute 729
#define sipName_QGeoPositionInfo__Attribute &sipStrings_QtPositioning[729]
#define sipNameNr_757 757
#define sipName_757 &sipStrings_QtPositioning[757]
#define sipNameNr_setNotificationParameters 784
#define sipName_setNotificationParameters &sipStrings_QtPositioning[784]
#define sipNameNr_810 810
#define sipName_810 &sipStrings_QtPositioning[810]
#define sipNameNr_userEquivalentRangeError 835
#define sipName_userEquivalentRangeError &sipStrings_QtPositioning[835]
#define sipNameNr_parsePosInfoFromNmeaData 860
#define sipName_parsePosInfoFromNmeaData &sipStrings_QtPositioning[860]
#define sipNameNr_InsufficientPositionInfo 885
#define sipName_InsufficientPositionInfo &sipStrings_QtPositioning[885]
#define sipNameNr_QNmeaPositionInfoSource 910
#define sipName_QNmeaPositionInfoSource &sipStrings_QtPositioning[910]
#define sipNameNr_satellitesInViewUpdated 934
#define sipName_satellitesInViewUpdated &sipStrings_QtPositioning[934]
#define sipNameNr_QGeoSatelliteInfoSource 958
#define sipName_QGeoSatelliteInfoSource &sipStrings_QtPositioning[958]
#define sipNameNr_satellitesInUseUpdated 982
#define sipName_satellitesInUseUpdated &sipStrings_QtPositioning[982]
#define sipNameNr_setSatelliteIdentifier 1005
#define sipName_setSatelliteIdentifier &sipStrings_QtPositioning[1005]
#define sipNameNr_QGeoPositionInfoSource 1028
#define sipName_QGeoPositionInfoSource &sipStrings_QtPositioning[1028]
#define sipNameNr_notificationParameters 1051
#define sipName_notificationParameters &sipStrings_QtPositioning[1051]
#define sipNameNr_1074 1074
#define sipName_1074 &sipStrings_QtPositioning[1074]
#define sipNameNr_minimumUpdateInterval 1096
#define sipName_minimumUpdateInterval &sipStrings_QtPositioning[1096]
#define sipNameNr_AllPositioningMethods 1118
#define sipName_AllPositioningMethods &sipStrings_QtPositioning[1118]
#define sipNameNr_DegreesMinutesSeconds 1140
#define sipName_DegreesMinutesSeconds &sipStrings_QtPositioning[1140]
#define sipNameNr_DegreesWithHemisphere 1162
#define sipName_DegreesWithHemisphere &sipStrings_QtPositioning[1162]
#define sipNameNr_setPositionInfoSource 1184
#define sipName_setPositionInfoSource &sipStrings_QtPositioning[1184]
#define sipNameNr_AnyAreaMonitorFeature 1206
#define sipName_AnyAreaMonitorFeature &sipStrings_QtPositioning[1206]
#define sipNameNr_QGeoAreaMonitorSource 1228
#define sipName_QGeoAreaMonitorSource &sipStrings_QtPositioning[1228]
#define sipNameNr_boundingGeoRectangle 1250
#define sipName_boundingGeoRectangle &sipStrings_QtPositioning[1250]
#define sipNameNr_QGeoShape__ShapeType 1271
#define sipName_QGeoShape__ShapeType &sipStrings_QtPositioning[1271]
#define sipNameNr_NoPositioningMethods 1292
#define sipName_NoPositioningMethods &sipStrings_QtPositioning[1292]
#define sipNameNr_atDistanceAndAzimuth 1313
#define sipName_atDistanceAndAzimuth &sipStrings_QtPositioning[1313]
#define sipNameNr_satelliteIdentifier 1334
#define sipName_satelliteIdentifier &sipStrings_QtPositioning[1334]
#define sipNameNr_createDefaultSource 1354
#define sipName_createDefaultSource &sipStrings_QtPositioning[1354]
#define sipNameNr_AreaMonitorFeatures 66
#define sipName_AreaMonitorFeatures &sipStrings_QtPositioning[66]
#define sipNameNr_QGeoAreaMonitorInfo 1374
#define sipName_QGeoAreaMonitorInfo &sipStrings_QtPositioning[1374]
#define sipNameNr_PyQt5_QtPositioning 1394
#define sipName_PyQt5_QtPositioning &sipStrings_QtPositioning[1394]
#define sipNameNr_setSatelliteSystem 1414
#define sipName_setSatelliteSystem &sipStrings_QtPositioning[1414]
#define sipNameNr_PositioningMethods 24
#define sipName_PositioningMethods &sipStrings_QtPositioning[24]
#define sipNameNr_HorizontalAccuracy 1433
#define sipName_HorizontalAccuracy &sipStrings_QtPositioning[1433]
#define sipNameNr_containsCoordinate 1452
#define sipName_containsCoordinate &sipStrings_QtPositioning[1452]
#define sipNameNr_positionInfoSource 1471
#define sipName_positionInfoSource &sipStrings_QtPositioning[1471]
#define sipNameNr_AreaMonitorFeature 151
#define sipName_AreaMonitorFeature &sipStrings_QtPositioning[151]
#define sipNameNr_UnknownSourceError 1490
#define sipName_UnknownSourceError &sipStrings_QtPositioning[1490]
#define sipNameNr_setSignalStrength 1509
#define sipName_setSignalStrength &sipStrings_QtPositioning[1509]
#define sipNameNr_QGeoSatelliteInfo 1527
#define sipName_QGeoSatelliteInfo &sipStrings_QtPositioning[1527]
#define sipNameNr_lastKnownPosition 1545
#define sipName_lastKnownPosition &sipStrings_QtPositioning[1545]
#define sipNameNr_PositioningMethod 110
#define sipName_PositioningMethod &sipStrings_QtPositioning[110]
#define sipNameNr_MagneticVariation 1563
#define sipName_MagneticVariation &sipStrings_QtPositioning[1563]
#define sipNameNr_replaceCoordinate 1581
#define sipName_replaceCoordinate &sipStrings_QtPositioning[1581]
#define sipNameNr_InvalidCoordinate 1599
#define sipName_InvalidCoordinate &sipStrings_QtPositioning[1599]
#define sipNameNr_setUpdateInterval 1617
#define sipName_setUpdateInterval &sipStrings_QtPositioning[1617]
#define sipNameNr_VerticalAccuracy 1635
#define sipName_VerticalAccuracy &sipStrings_QtPositioning[1635]
#define sipNameNr_QGeoPositionInfo 1652
#define sipName_QGeoPositionInfo &sipStrings_QtPositioning[1652]
#define sipNameNr_removeCoordinate 1669
#define sipName_removeCoordinate &sipStrings_QtPositioning[1669]
#define sipNameNr_insertCoordinate 1686
#define sipName_insertCoordinate &sipStrings_QtPositioning[1686]
#define sipNameNr_CoordinateFormat 329
#define sipName_CoordinateFormat &sipStrings_QtPositioning[329]
#define sipNameNr_availableSources 1703
#define sipName_availableSources &sipStrings_QtPositioning[1703]
#define sipNameNr_disconnectNotify 1720
#define sipName_disconnectNotify &sipStrings_QtPositioning[1720]
#define sipNameNr_satelliteSystem 1737
#define sipName_satelliteSystem &sipStrings_QtPositioning[1737]
#define sipNameNr_SatelliteSystem 297
#define sipName_SatelliteSystem &sipStrings_QtPositioning[297]
#define sipNameNr_extendRectangle 1753
#define sipName_extendRectangle &sipStrings_QtPositioning[1753]
#define sipNameNr_positionUpdated 1769
#define sipName_positionUpdated &sipStrings_QtPositioning[1769]
#define sipNameNr_removeAttribute 1785
#define sipName_removeAttribute &sipStrings_QtPositioning[1785]
#define sipNameNr_startMonitoring 1801
#define sipName_startMonitoring &sipStrings_QtPositioning[1801]
#define sipNameNr_isTextGenerated 1817
#define sipName_isTextGenerated &sipStrings_QtPositioning[1817]
#define sipNameNr_SimulationMode 1833
#define sipName_SimulationMode &sipStrings_QtPositioning[1833]
#define sipNameNr_requestTimeout 1848
#define sipName_requestTimeout &sipStrings_QtPositioning[1848]
#define sipNameNr_signalStrength 1863
#define sipName_signalStrength &sipStrings_QtPositioning[1863]
#define sipNameNr_setBoundingBox 1878
#define sipName_setBoundingBox &sipStrings_QtPositioning[1878]
#define sipNameNr_DegreesMinutes 1893
#define sipName_DegreesMinutes &sipStrings_QtPositioning[1893]
#define sipNameNr_CoordinateType 455
#define sipName_CoordinateType &sipStrings_QtPositioning[455]
#define sipNameNr_QGeoCoordinate 1908
#define sipName_QGeoCoordinate &sipStrings_QtPositioning[1908]
#define sipNameNr_monitorExpired 1923
#define sipName_monitorExpired &sipStrings_QtPositioning[1923]
#define sipNameNr_activeMonitors 1938
#define sipName_activeMonitors &sipStrings_QtPositioning[1938]
#define sipNameNr_stopMonitoring 1953
#define sipName_stopMonitoring &sipStrings_QtPositioning[1953]
#define sipNameNr_setCountryCode 1968
#define sipName_setCountryCode &sipStrings_QtPositioning[1968]
#define sipNameNr_updateInterval 1983
#define sipName_updateInterval &sipStrings_QtPositioning[1983]
#define sipNameNr_setBottomRight 1998
#define sipName_setBottomRight &sipStrings_QtPositioning[1998]
#define sipNameNr_RectangleType 2013
#define sipName_RectangleType &sipStrings_QtPositioning[2013]
#define sipNameNr_QGeoRectangle 2027
#define sipName_QGeoRectangle &sipStrings_QtPositioning[2027]
#define sipNameNr_updateTimeout 2041
#define sipName_updateTimeout &sipStrings_QtPositioning[2041]
#define sipNameNr_VerticalSpeed 2055
#define sipName_VerticalSpeed &sipStrings_QtPositioning[2055]
#define sipNameNr_addCoordinate 2069
#define sipName_addCoordinate &sipStrings_QtPositioning[2069]
#define sipNameNr_setCoordinate 2083
#define sipName_setCoordinate &sipStrings_QtPositioning[2083]
#define sipNameNr_requestUpdate 2097
#define sipName_requestUpdate &sipStrings_QtPositioning[2097]
#define sipNameNr_setPersistent 2111
#define sipName_setPersistent &sipStrings_QtPositioning[2111]
#define sipNameNr_setExpiration 2125
#define sipName_setExpiration &sipStrings_QtPositioning[2125]
#define sipNameNr_setPostalCode 2139
#define sipName_setPostalCode &sipStrings_QtPositioning[2139]
#define sipNameNr_setBottomLeft 2153
#define sipName_setBottomLeft &sipStrings_QtPositioning[2153]
#define sipNameNr_connectNotify 1723
#define sipName_connectNotify &sipStrings_QtPositioning[1723]
#define sipNameNr_RealTimeMode 2167
#define sipName_RealTimeMode &sipStrings_QtPositioning[2167]
#define sipNameNr_startUpdates 2180
#define sipName_startUpdates &sipStrings_QtPositioning[2180]
#define sipNameNr_setTimestamp 2193
#define sipName_setTimestamp &sipStrings_QtPositioning[2193]
#define sipNameNr_coordinateAt 2206
#define sipName_coordinateAt &sipStrings_QtPositioning[2206]
#define sipNameNr_QGeoLocation 2219
#define sipName_QGeoLocation &sipStrings_QtPositioning[2219]
#define sipNameNr_setLongitude 2232
#define sipName_setLongitude &sipStrings_QtPositioning[2232]
#define sipNameNr_Coordinate3D 2245
#define sipName_Coordinate3D &sipStrings_QtPositioning[2245]
#define sipNameNr_Coordinate2D 2258
#define sipName_Coordinate2D &sipStrings_QtPositioning[2258]
#define sipNameNr_extendCircle 2271
#define sipName_extendCircle &sipStrings_QtPositioning[2271]
#define sipNameNr_createSource 2284
#define sipName_createSource &sipStrings_QtPositioning[2284]
#define sipNameNr_isPersistent 2297
#define sipName_isPersistent &sipStrings_QtPositioning[2297]
#define sipNameNr_hasAttribute 2310
#define sipName_hasAttribute &sipStrings_QtPositioning[2310]
#define sipNameNr_setAttribute 2323
#define sipName_setAttribute &sipStrings_QtPositioning[2323]
#define sipNameNr_extendShape 2336
#define sipName_extendShape &sipStrings_QtPositioning[2336]
#define sipNameNr_PolygonType 2348
#define sipName_PolygonType &sipStrings_QtPositioning[2348]
#define sipNameNr_stopUpdates 2360
#define sipName_stopUpdates &sipStrings_QtPositioning[2360]
#define sipNameNr_ClosedError 2372
#define sipName_ClosedError &sipStrings_QtPositioning[2372]
#define sipNameNr_GroundSpeed 2384
#define sipName_GroundSpeed &sipStrings_QtPositioning[2384]
#define sipNameNr_QGeoPolygon 2396
#define sipName_QGeoPolygon &sipStrings_QtPositioning[2396]
#define sipNameNr_boundingBox 2408
#define sipName_boundingBox &sipStrings_QtPositioning[2408]
#define sipNameNr_setAltitude 2420
#define sipName_setAltitude &sipStrings_QtPositioning[2420]
#define sipNameNr_setLatitude 2432
#define sipName_setLatitude &sipStrings_QtPositioning[2432]
#define sipNameNr_areaEntered 2444
#define sipName_areaEntered &sipStrings_QtPositioning[2444]
#define sipNameNr_setDistrict 2456
#define sipName_setDistrict &sipStrings_QtPositioning[2456]
#define sipNameNr_countryCode 2468
#define sipName_countryCode &sipStrings_QtPositioning[2468]
#define sipNameNr_QGeoAddress 2480
#define sipName_QGeoAddress &sipStrings_QtPositioning[2480]
#define sipNameNr_AccessError 2492
#define sipName_AccessError &sipStrings_QtPositioning[2492]
#define sipNameNr_setTopRight 2504
#define sipName_setTopRight &sipStrings_QtPositioning[2504]
#define sipNameNr_customEvent 2516
#define sipName_customEvent &sipStrings_QtPositioning[2516]
#define sipNameNr_eventFilter 2528
#define sipName_eventFilter &sipStrings_QtPositioning[2528]
#define sipNameNr_UnknownType 2540
#define sipName_UnknownType &sipStrings_QtPositioning[2540]
#define sipNameNr_bottomRight 2552
#define sipName_bottomRight &sipStrings_QtPositioning[2552]
#define sipNameNr_updateMode 2564
#define sipName_updateMode &sipStrings_QtPositioning[2564]
#define sipNameNr_UpdateMode 195
#define sipName_UpdateMode &sipStrings_QtPositioning[195]
#define sipNameNr_CircleType 2575
#define sipName_CircleType &sipStrings_QtPositioning[2575]
#define sipNameNr_setAddress 2586
#define sipName_setAddress &sipStrings_QtPositioning[2586]
#define sipNameNr_distanceUp 2597
#define sipName_distanceUp &sipStrings_QtPositioning[2597]
#define sipNameNr_distanceTo 2608
#define sipName_distanceTo &sipStrings_QtPositioning[2608]
#define sipNameNr_coordinate 2619
#define sipName_coordinate &sipStrings_QtPositioning[2619]
#define sipNameNr_QGeoCircle 2630
#define sipName_QGeoCircle &sipStrings_QtPositioning[2630]
#define sipNameNr_areaExited 2641
#define sipName_areaExited &sipStrings_QtPositioning[2641]
#define sipNameNr_sourceName 2652
#define sipName_sourceName &sipStrings_QtPositioning[2652]
#define sipNameNr_expiration 2663
#define sipName_expiration &sipStrings_QtPositioning[2663]
#define sipNameNr_identifier 2674
#define sipName_identifier &sipStrings_QtPositioning[2674]
#define sipNameNr_postalCode 2685
#define sipName_postalCode &sipStrings_QtPositioning[2685]
#define sipNameNr_setCountry 2696
#define sipName_setCountry &sipStrings_QtPositioning[2696]
#define sipNameNr_bottomLeft 2707
#define sipName_bottomLeft &sipStrings_QtPositioning[2707]
#define sipNameNr_setTopLeft 2718
#define sipName_setTopLeft &sipStrings_QtPositioning[2718]
#define sipNameNr_childEvent 2729
#define sipName_childEvent &sipStrings_QtPositioning[2729]
#define sipNameNr_timerEvent 2740
#define sipName_timerEvent &sipStrings_QtPositioning[2740]
#define sipNameNr_translated 2751
#define sipName_translated &sipStrings_QtPositioning[2751]
#define sipNameNr_intersects 2762
#define sipName_intersects &sipStrings_QtPositioning[2762]
#define sipNameNr___rshift__ 2773
#define sipName___rshift__ &sipStrings_QtPositioning[2773]
#define sipNameNr___lshift__ 2784
#define sipName___lshift__ &sipStrings_QtPositioning[2784]
#define sipNameNr___invert__ 2795
#define sipName___invert__ &sipStrings_QtPositioning[2795]
#define sipNameNr_ShapeType 1282
#define sipName_ShapeType &sipStrings_QtPositioning[1282]
#define sipNameNr_Elevation 2806
#define sipName_Elevation &sipStrings_QtPositioning[2806]
#define sipNameNr_timestamp 2816
#define sipName_timestamp &sipStrings_QtPositioning[2816]
#define sipNameNr_Attribute 519
#define sipName_Attribute &sipStrings_QtPositioning[519]
#define sipNameNr_indexFrom 2826
#define sipName_indexFrom &sipStrings_QtPositioning[2826]
#define sipNameNr_azimuthTo 2836
#define sipName_azimuthTo &sipStrings_QtPositioning[2836]
#define sipNameNr_longitude 2846
#define sipName_longitude &sipStrings_QtPositioning[2846]
#define sipNameNr_setRadius 2856
#define sipName_setRadius &sipStrings_QtPositioning[2856]
#define sipNameNr_setCenter 2866
#define sipName_setCenter &sipStrings_QtPositioning[2866]
#define sipNameNr_QGeoShape 2876
#define sipName_QGeoShape &sipStrings_QtPositioning[2876]
#define sipNameNr_setStreet 2886
#define sipName_setStreet &sipStrings_QtPositioning[2886]
#define sipNameNr_setCounty 2896
#define sipName_setCounty &sipStrings_QtPositioning[2896]
#define sipNameNr_directory 2906
#define sipName_directory &sipStrings_QtPositioning[2906]
#define sipNameNr_setHeight 2916
#define sipName_setHeight &sipStrings_QtPositioning[2916]
#define sipNameNr_Undefined 2926
#define sipName_Undefined &sipStrings_QtPositioning[2926]
#define sipNameNr_setDevice 2936
#define sipName_setDevice &sipStrings_QtPositioning[2936]
#define sipNameNr_attribute 2946
#define sipName_attribute &sipStrings_QtPositioning[2946]
#define sipNameNr_translate 2956
#define sipName_translate &sipStrings_QtPositioning[2956]
#define sipNameNr_precision 2966
#define sipName_precision &sipStrings_QtPositioning[2966]
#define sipNameNr_Direction 2976
#define sipName_Direction &sipStrings_QtPositioning[2976]
#define sipNameNr_PathType 2986
#define sipName_PathType &sipStrings_QtPositioning[2986]
#define sipNameNr_QGeoPath 2995
#define sipName_QGeoPath &sipStrings_QtPositioning[2995]
#define sipNameNr_altitude 3004
#define sipName_altitude &sipStrings_QtPositioning[3004]
#define sipNameNr_latitude 3013
#define sipName_latitude &sipStrings_QtPositioning[3013]
#define sipNameNr_district 3022
#define sipName_district &sipStrings_QtPositioning[3022]
#define sipNameNr_setState 3031
#define sipName_setState &sipStrings_QtPositioning[3031]
#define sipNameNr_nameType 3040
#define sipName_nameType &sipStrings_QtPositioning[3040]
#define sipNameNr_setWidth 3049
#define sipName_setWidth &sipStrings_QtPositioning[3049]
#define sipNameNr_topRight 3058
#define sipName_topRight &sipStrings_QtPositioning[3058]
#define sipNameNr_toString 3067
#define sipName_toString &sipStrings_QtPositioning[3067]
#define sipNameNr_contains 3076
#define sipName_contains &sipStrings_QtPositioning[3076]
#define sipNameNr___hash__ 3085
#define sipName___hash__ &sipStrings_QtPositioning[3085]
#define sipNameNr___bool__ 3094
#define sipName___bool__ &sipStrings_QtPositioning[3094]
#define sipNameNr___ixor__ 3103
#define sipName___ixor__ &sipStrings_QtPositioning[3103]
#define sipNameNr___iand__ 3112
#define sipName___iand__ &sipStrings_QtPositioning[3112]
#define sipNameNr_GLONASS 3121
#define sipName_GLONASS &sipStrings_QtPositioning[3121]
#define sipNameNr_Azimuth 1326
#define sipName_Azimuth &sipStrings_QtPositioning[1326]
#define sipNameNr_indexTo 3129
#define sipName_indexTo &sipStrings_QtPositioning[3129]
#define sipNameNr_Degrees 3137
#define sipName_Degrees &sipStrings_QtPositioning[3137]
#define sipNameNr_setArea 3145
#define sipName_setArea &sipStrings_QtPositioning[3145]
#define sipNameNr_setName 3153
#define sipName_setName &sipStrings_QtPositioning[3153]
#define sipNameNr_setCity 3161
#define sipName_setCity &sipStrings_QtPositioning[3161]
#define sipNameNr_setText 3169
#define sipName_setText &sipStrings_QtPositioning[3169]
#define sipNameNr_country 3177
#define sipName_country &sipStrings_QtPositioning[3177]
#define sipNameNr_address 3185
#define sipName_address &sipStrings_QtPositioning[3185]
#define sipNameNr_NoError 3193
#define sipName_NoError &sipStrings_QtPositioning[3193]
#define sipNameNr_timeout 3201
#define sipName_timeout &sipStrings_QtPositioning[3201]
#define sipNameNr_setPath 3209
#define sipName_setPath &sipStrings_QtPositioning[3209]
#define sipNameNr_filters 3217
#define sipName_filters &sipStrings_QtPositioning[3217]
#define sipNameNr_isEmpty 3225
#define sipName_isEmpty &sipStrings_QtPositioning[3225]
#define sipNameNr_options 3233
#define sipName_options &sipStrings_QtPositioning[3233]
#define sipNameNr_topLeft 3241
#define sipName_topLeft &sipStrings_QtPositioning[3241]
#define sipNameNr_isValid 3249
#define sipName_isValid &sipStrings_QtPositioning[3249]
#define sipNameNr___xor__ 3257
#define sipName___xor__ &sipStrings_QtPositioning[3257]
#define sipNameNr___ior__ 3265
#define sipName___ior__ &sipStrings_QtPositioning[3265]
#define sipNameNr___and__ 3273
#define sipName___and__ &sipStrings_QtPositioning[3273]
#define sipNameNr___int__ 3281
#define sipName___int__ &sipStrings_QtPositioning[3281]
#define sipNameNr_radius 3289
#define sipName_radius &sipStrings_QtPositioning[3289]
#define sipNameNr_street 3296
#define sipName_street &sipStrings_QtPositioning[3296]
#define sipNameNr_county 3303
#define sipName_county &sipStrings_QtPositioning[3303]
#define sipNameNr_united 3310
#define sipName_united &sipStrings_QtPositioning[3310]
#define sipNameNr_proper 3317
#define sipName_proper &sipStrings_QtPositioning[3317]
#define sipNameNr_value9 3324
#define sipName_value9 &sipStrings_QtPositioning[3324]
#define sipNameNr_value8 3331
#define sipName_value8 &sipStrings_QtPositioning[3331]
#define sipNameNr_value7 3338
#define sipName_value7 &sipStrings_QtPositioning[3338]
#define sipNameNr_value6 3345
#define sipName_value6 &sipStrings_QtPositioning[3345]
#define sipNameNr_value5 3352
#define sipName_value5 &sipStrings_QtPositioning[3352]
#define sipNameNr_value4 3359
#define sipName_value4 &sipStrings_QtPositioning[3359]
#define sipNameNr_value3 3366
#define sipName_value3 &sipStrings_QtPositioning[3366]
#define sipNameNr_value2 3373
#define sipName_value2 &sipStrings_QtPositioning[3373]
#define sipNameNr_value1 3380
#define sipName_value1 &sipStrings_QtPositioning[3380]
#define sipNameNr_value0 3387
#define sipName_value0 &sipStrings_QtPositioning[3387]
#define sipNameNr_center 3394
#define sipName_center &sipStrings_QtPositioning[3394]
#define sipNameNr_symbol 3401
#define sipName_symbol &sipStrings_QtPositioning[3401]
#define sipNameNr_height 3408
#define sipName_height &sipStrings_QtPositioning[3408]
#define sipNameNr_suffix 3415
#define sipName_suffix &sipStrings_QtPositioning[3415]
#define sipNameNr_prefix 3422
#define sipName_prefix &sipStrings_QtPositioning[3422]
#define sipNameNr_device 3429
#define sipName_device &sipStrings_QtPositioning[3429]
#define sipNameNr_locale 3436
#define sipName_locale &sipStrings_QtPositioning[3436]
#define sipNameNr_format 3443
#define sipName_format &sipStrings_QtPositioning[3443]
#define sipNameNr_length 3450
#define sipName_length &sipStrings_QtPositioning[3450]
#define sipNameNr_parent 3457
#define sipName_parent &sipStrings_QtPositioning[3457]
#define sipNameNr___ne__ 3464
#define sipName___ne__ &sipStrings_QtPositioning[3464]
#define sipNameNr___eq__ 3471
#define sipName___eq__ &sipStrings_QtPositioning[3471]
#define sipNameNr___or__ 3478
#define sipName___or__ &sipStrings_QtPositioning[3478]
#define sipNameNr_Error 371
#define sipName_Error &sipStrings_QtPositioning[371]
#define sipNameNr_error 3485
#define sipName_error &sipStrings_QtPositioning[3485]
#define sipNameNr_width 3491
#define sipName_width &sipStrings_QtPositioning[3491]
#define sipNameNr_clear 3497
#define sipName_clear &sipStrings_QtPositioning[3497]
#define sipNameNr_event 3503
#define sipName_event &sipStrings_QtPositioning[3503]
#define sipNameNr_msecs 3509
#define sipName_msecs &sipStrings_QtPositioning[3509]
#define sipNameNr_state 3515
#define sipName_state &sipStrings_QtPositioning[3515]
#define sipNameNr_area 3521
#define sipName_area &sipStrings_QtPositioning[3521]
#define sipNameNr_city 3526
#define sipName_city &sipStrings_QtPositioning[3526]
#define sipNameNr_text 3531
#define sipName_text &sipStrings_QtPositioning[3531]
#define sipNameNr_path 3536
#define sipName_path &sipStrings_QtPositioning[3536]
#define sipNameNr_mode 3541
#define sipName_mode &sipStrings_QtPositioning[3541]
#define sipNameNr_name 3546
#define sipName_name &sipStrings_QtPositioning[3546]
#define sipNameNr_base 3551
#define sipName_base &sipStrings_QtPositioning[3551]
#define sipNameNr_size 3556
#define sipName_size &sipStrings_QtPositioning[3556]
#define sipNameNr_type 3561
#define sipName_type &sipStrings_QtPositioning[3561]
#define sipNameNr_from 3566
#define sipName_from &sipStrings_QtPositioning[3566]
#define sipNameNr_sort 3571
#define sipName_sort &sipStrings_QtPositioning[3571]
#define sipNameNr_GPS 3576
#define sipName_GPS &sipStrings_QtPositioning[3576]
#define sipNameNr_pid 3580
#define sipName_pid &sipStrings_QtPositioning[3580]

#define sipMalloc                   sipAPI_QtPositioning->api_malloc
#define sipFree                     sipAPI_QtPositioning->api_free
#define sipBuildResult              sipAPI_QtPositioning->api_build_result
#define sipCallMethod               sipAPI_QtPositioning->api_call_method
#define sipCallProcedureMethod      sipAPI_QtPositioning->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_QtPositioning->api_call_error_handler
#define sipParseResultEx            sipAPI_QtPositioning->api_parse_result_ex
#define sipParseResult              sipAPI_QtPositioning->api_parse_result
#define sipParseArgs                sipAPI_QtPositioning->api_parse_args
#define sipParseKwdArgs             sipAPI_QtPositioning->api_parse_kwd_args
#define sipParsePair                sipAPI_QtPositioning->api_parse_pair
#define sipInstanceDestroyed        sipAPI_QtPositioning->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_QtPositioning->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_QtPositioning->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_QtPositioning->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_QtPositioning->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_QtPositioning->api_convert_to_void_ptr
#define sipAddException             sipAPI_QtPositioning->api_add_exception
#define sipNoFunction               sipAPI_QtPositioning->api_no_function
#define sipNoMethod                 sipAPI_QtPositioning->api_no_method
#define sipAbstractMethod           sipAPI_QtPositioning->api_abstract_method
#define sipBadClass                 sipAPI_QtPositioning->api_bad_class
#define sipBadCatcherResult         sipAPI_QtPositioning->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_QtPositioning->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_QtPositioning->api_bad_operator_arg
#define sipTrace                    sipAPI_QtPositioning->api_trace
#define sipTransferBack             sipAPI_QtPositioning->api_transfer_back
#define sipTransferTo               sipAPI_QtPositioning->api_transfer_to
#define sipTransferBreak            sipAPI_QtPositioning->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_QtPositioning->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_QtPositioning->api_wrapper_type
#define sipWrapperType_Type         sipAPI_QtPositioning->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_QtPositioning->api_voidptr_type
#define sipGetPyObject              sipAPI_QtPositioning->api_get_pyobject
#define sipGetAddress               sipAPI_QtPositioning->api_get_address
#define sipGetMixinAddress          sipAPI_QtPositioning->api_get_mixin_address
#define sipGetCppPtr                sipAPI_QtPositioning->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_QtPositioning->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_QtPositioning->api_is_py_method
#define sipCallHook                 sipAPI_QtPositioning->api_call_hook
#define sipEndThread                sipAPI_QtPositioning->api_end_thread
#define sipConnectRx                sipAPI_QtPositioning->api_connect_rx
#define sipDisconnectRx             sipAPI_QtPositioning->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_QtPositioning->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_QtPositioning->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_QtPositioning->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_QtPositioning->api_add_type_instance
#define sipFreeSipslot              sipAPI_QtPositioning->api_free_sipslot
#define sipSameSlot                 sipAPI_QtPositioning->api_same_slot
#define sipPySlotExtend             sipAPI_QtPositioning->api_pyslot_extend
#define sipConvertRx                sipAPI_QtPositioning->api_convert_rx
#define sipAddDelayedDtor           sipAPI_QtPositioning->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_QtPositioning->api_can_convert_to_type
#define sipConvertToType            sipAPI_QtPositioning->api_convert_to_type
#define sipForceConvertToType       sipAPI_QtPositioning->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_QtPositioning->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_QtPositioning->api_convert_to_enum
#define sipConvertToBool            sipAPI_QtPositioning->api_convert_to_bool
#define sipReleaseType              sipAPI_QtPositioning->api_release_type
#define sipConvertFromType          sipAPI_QtPositioning->api_convert_from_type
#define sipConvertFromNewType       sipAPI_QtPositioning->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_QtPositioning->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_QtPositioning->api_convert_from_enum
#define sipGetState                 sipAPI_QtPositioning->api_get_state
#define sipExportSymbol             sipAPI_QtPositioning->api_export_symbol
#define sipImportSymbol             sipAPI_QtPositioning->api_import_symbol
#define sipFindType                 sipAPI_QtPositioning->api_find_type
#define sipFindNamedEnum            sipAPI_QtPositioning->api_find_named_enum
#define sipBytes_AsChar             sipAPI_QtPositioning->api_bytes_as_char
#define sipBytes_AsString           sipAPI_QtPositioning->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_QtPositioning->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_QtPositioning->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_QtPositioning->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_QtPositioning->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_QtPositioning->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_QtPositioning->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_QtPositioning->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_QtPositioning->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_QtPositioning->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_QtPositioning->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_QtPositioning->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_QtPositioning->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_QtPositioning->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_QtPositioning->api_save_slot
#define sipClearAnySlotReference    sipAPI_QtPositioning->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_QtPositioning->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_QtPositioning->api_deprecated
#define sipGetReference             sipAPI_QtPositioning->api_get_reference
#define sipKeepReference            sipAPI_QtPositioning->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_QtPositioning->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_QtPositioning->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_QtPositioning->api_type_from_py_type_object
#define sipTypeScope                sipAPI_QtPositioning->api_type_scope
#define sipResolveTypedef           sipAPI_QtPositioning->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_QtPositioning->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_QtPositioning->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_QtPositioning->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_QtPositioning->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_QtPositioning->api_enable_overflow_checking
#define sipInitMixin                sipAPI_QtPositioning->api_init_mixin
#define sipExportModule             sipAPI_QtPositioning->api_export_module
#define sipInitModule               sipAPI_QtPositioning->api_init_module
#define sipGetInterpreter           sipAPI_QtPositioning->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_QtPositioning->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_QtPositioning->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_QtPositioning->api_get_type_user_data
#define sipPyTypeDict               sipAPI_QtPositioning->api_py_type_dict
#define sipPyTypeName               sipAPI_QtPositioning->api_py_type_name
#define sipGetCFunction             sipAPI_QtPositioning->api_get_c_function
#define sipGetMethod                sipAPI_QtPositioning->api_get_method
#define sipFromMethod               sipAPI_QtPositioning->api_from_method
#define sipGetDate                  sipAPI_QtPositioning->api_get_date
#define sipFromDate                 sipAPI_QtPositioning->api_from_date
#define sipGetDateTime              sipAPI_QtPositioning->api_get_datetime
#define sipFromDateTime             sipAPI_QtPositioning->api_from_datetime
#define sipGetTime                  sipAPI_QtPositioning->api_get_time
#define sipFromTime                 sipAPI_QtPositioning->api_from_time
#define sipIsUserType               sipAPI_QtPositioning->api_is_user_type
#define sipGetFrame                 sipAPI_QtPositioning->api_get_frame
#define sipCheckPluginForType       sipAPI_QtPositioning->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_QtPositioning->api_unicode_new
#define sipUnicodeWrite             sipAPI_QtPositioning->api_unicode_write
#define sipUnicodeData              sipAPI_QtPositioning->api_unicode_data
#define sipGetBufferInfo            sipAPI_QtPositioning->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_QtPositioning->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_QtPositioning->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_QtPositioning->api_is_derived_class
#define sipGetUserObject            sipAPI_QtPositioning->api_get_user_object
#define sipSetUserObject            sipAPI_QtPositioning->api_set_user_object
#define sipRegisterEventHandler     sipAPI_QtPositioning->api_register_event_handler
#define sipLong_AsChar              sipAPI_QtPositioning->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_QtPositioning->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_QtPositioning->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_QtPositioning->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_QtPositioning->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_QtPositioning->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_QtPositioning->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_QtPositioning->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_QtPositioning->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_QtPositioning->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_QtPositioning->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_QtPositioning->api_map_string_to_class
#define sipMapIntToClass            sipAPI_QtPositioning->api_map_int_to_class
#define sipFindClass                sipAPI_QtPositioning->api_find_class
#define sipFindMappedType           sipAPI_QtPositioning->api_find_mapped_type
#define sipConvertToArray           sipAPI_QtPositioning->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_QtPositioning->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_QtPositioning->api_enable_gc
#define sipPrintObject              sipAPI_QtPositioning->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_QtPositioning->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_QtPositioning[];

#define sipType_QGeoAddress sipExportedTypes_QtPositioning[0]
#define sipClass_QGeoAddress sipExportedTypes_QtPositioning[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoAddress;

#define sipType_QGeoAreaMonitorInfo sipExportedTypes_QtPositioning[1]
#define sipClass_QGeoAreaMonitorInfo sipExportedTypes_QtPositioning[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoAreaMonitorInfo;

#define sipType_QGeoAreaMonitorSource sipExportedTypes_QtPositioning[2]
#define sipClass_QGeoAreaMonitorSource sipExportedTypes_QtPositioning[2]->u.td_wrapper_type

#define sipType_QGeoAreaMonitorSource_AreaMonitorFeature sipExportedTypes_QtPositioning[3]
#define sipEnum_QGeoAreaMonitorSource_AreaMonitorFeature sipExportedTypes_QtPositioning[3]->u.td_py_type

#define sipType_QGeoAreaMonitorSource_Error sipExportedTypes_QtPositioning[5]
#define sipEnum_QGeoAreaMonitorSource_Error sipExportedTypes_QtPositioning[5]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoAreaMonitorSource;

#define sipType_QGeoAreaMonitorSource_AreaMonitorFeatures sipExportedTypes_QtPositioning[4]
#define sipClass_QGeoAreaMonitorSource_AreaMonitorFeatures sipExportedTypes_QtPositioning[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoAreaMonitorSource_AreaMonitorFeatures;

#define sipType_QGeoShape sipExportedTypes_QtPositioning[25]
#define sipClass_QGeoShape sipExportedTypes_QtPositioning[25]->u.td_wrapper_type

#define sipType_QGeoShape_ShapeType sipExportedTypes_QtPositioning[26]
#define sipEnum_QGeoShape_ShapeType sipExportedTypes_QtPositioning[26]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoShape;

#define sipType_QGeoCircle sipExportedTypes_QtPositioning[6]
#define sipClass_QGeoCircle sipExportedTypes_QtPositioning[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoCircle;

#define sipType_QGeoCoordinate sipExportedTypes_QtPositioning[7]
#define sipClass_QGeoCoordinate sipExportedTypes_QtPositioning[7]->u.td_wrapper_type

#define sipType_QGeoCoordinate_CoordinateFormat sipExportedTypes_QtPositioning[8]
#define sipEnum_QGeoCoordinate_CoordinateFormat sipExportedTypes_QtPositioning[8]->u.td_py_type

#define sipType_QGeoCoordinate_CoordinateType sipExportedTypes_QtPositioning[9]
#define sipEnum_QGeoCoordinate_CoordinateType sipExportedTypes_QtPositioning[9]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoCoordinate;

#define sipType_QGeoLocation sipExportedTypes_QtPositioning[10]
#define sipClass_QGeoLocation sipExportedTypes_QtPositioning[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoLocation;

#define sipType_QGeoPath sipExportedTypes_QtPositioning[11]
#define sipClass_QGeoPath sipExportedTypes_QtPositioning[11]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoPath;

#define sipType_QGeoPolygon sipExportedTypes_QtPositioning[12]
#define sipClass_QGeoPolygon sipExportedTypes_QtPositioning[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoPolygon;

#define sipType_QGeoPositionInfo sipExportedTypes_QtPositioning[13]
#define sipClass_QGeoPositionInfo sipExportedTypes_QtPositioning[13]->u.td_wrapper_type

#define sipType_QGeoPositionInfo_Attribute sipExportedTypes_QtPositioning[14]
#define sipEnum_QGeoPositionInfo_Attribute sipExportedTypes_QtPositioning[14]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoPositionInfo;

#define sipType_QGeoPositionInfoSource sipExportedTypes_QtPositioning[15]
#define sipClass_QGeoPositionInfoSource sipExportedTypes_QtPositioning[15]->u.td_wrapper_type

#define sipType_QGeoPositionInfoSource_PositioningMethod sipExportedTypes_QtPositioning[17]
#define sipEnum_QGeoPositionInfoSource_PositioningMethod sipExportedTypes_QtPositioning[17]->u.td_py_type

#define sipType_QGeoPositionInfoSource_Error sipExportedTypes_QtPositioning[16]
#define sipEnum_QGeoPositionInfoSource_Error sipExportedTypes_QtPositioning[16]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoPositionInfoSource;

#define sipType_QGeoPositionInfoSource_PositioningMethods sipExportedTypes_QtPositioning[18]
#define sipClass_QGeoPositionInfoSource_PositioningMethods sipExportedTypes_QtPositioning[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoPositionInfoSource_PositioningMethods;

#define sipType_QGeoRectangle sipExportedTypes_QtPositioning[19]
#define sipClass_QGeoRectangle sipExportedTypes_QtPositioning[19]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoRectangle;

#define sipType_QGeoSatelliteInfo sipExportedTypes_QtPositioning[20]
#define sipClass_QGeoSatelliteInfo sipExportedTypes_QtPositioning[20]->u.td_wrapper_type

#define sipType_QGeoSatelliteInfo_SatelliteSystem sipExportedTypes_QtPositioning[22]
#define sipEnum_QGeoSatelliteInfo_SatelliteSystem sipExportedTypes_QtPositioning[22]->u.td_py_type

#define sipType_QGeoSatelliteInfo_Attribute sipExportedTypes_QtPositioning[21]
#define sipEnum_QGeoSatelliteInfo_Attribute sipExportedTypes_QtPositioning[21]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoSatelliteInfo;

#define sipType_QGeoSatelliteInfoSource sipExportedTypes_QtPositioning[23]
#define sipClass_QGeoSatelliteInfoSource sipExportedTypes_QtPositioning[23]->u.td_wrapper_type

#define sipType_QGeoSatelliteInfoSource_Error sipExportedTypes_QtPositioning[24]
#define sipEnum_QGeoSatelliteInfoSource_Error sipExportedTypes_QtPositioning[24]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QGeoSatelliteInfoSource;

#define sipType_QNmeaPositionInfoSource sipExportedTypes_QtPositioning[30]
#define sipClass_QNmeaPositionInfoSource sipExportedTypes_QtPositioning[30]->u.td_wrapper_type

#define sipType_QNmeaPositionInfoSource_UpdateMode sipExportedTypes_QtPositioning[31]
#define sipEnum_QNmeaPositionInfoSource_UpdateMode sipExportedTypes_QtPositioning[31]->u.td_py_type

extern sipClassTypeDef sipTypeDef_QtPositioning_QNmeaPositionInfoSource;

#define sipType_QList_0100QGeoSatelliteInfo sipExportedTypes_QtPositioning[29]

extern sipMappedTypeDef sipTypeDef_QtPositioning_QList_0100QGeoSatelliteInfo;

#define sipType_QList_0100QGeoCoordinate sipExportedTypes_QtPositioning[28]

extern sipMappedTypeDef sipTypeDef_QtPositioning_QList_0100QGeoCoordinate;

#define sipType_QList_0100QGeoAreaMonitorInfo sipExportedTypes_QtPositioning[27]

extern sipMappedTypeDef sipTypeDef_QtPositioning_QList_0100QGeoAreaMonitorInfo;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_QtPositioning;
extern sipExportedModuleDef sipModuleAPI_QtPositioning;
extern sipTypeDef *sipExportedTypes_QtPositioning[];

#define sipType_QObject sipImportedTypes_QtPositioning_QtCore[6].it_td
#define sipClass_QObject sipImportedTypes_QtPositioning_QtCore[6].it_td->u.td_wrapper_type

#define sipType_QIODevice sipImportedTypes_QtPositioning_QtCore[4].it_td
#define sipClass_QIODevice sipImportedTypes_QtPositioning_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_QtPositioning_QtCore[3].it_td
#define sipClass_QEvent sipImportedTypes_QtPositioning_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_QtPositioning_QtCore[9].it_td
#define sipClass_QTimerEvent sipImportedTypes_QtPositioning_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_QtPositioning_QtCore[0].it_td
#define sipClass_QChildEvent sipImportedTypes_QtPositioning_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QDataStream sipImportedTypes_QtPositioning_QtCore[1].it_td
#define sipClass_QDataStream sipImportedTypes_QtPositioning_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QDateTime sipImportedTypes_QtPositioning_QtCore[2].it_td
#define sipClass_QDateTime sipImportedTypes_QtPositioning_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_QtPositioning_QtCore[5].it_td
#define sipClass_QMetaMethod sipImportedTypes_QtPositioning_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QStringList sipImportedTypes_QtPositioning_QtCore[8].it_td

#define sipType_QVariantMap sipImportedTypes_QtPositioning_QtCore[10].it_td

#define sipType_QString sipImportedTypes_QtPositioning_QtCore[7].it_td
extern sipImportedTypeDef sipImportedTypes_QtPositioning_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_QtPositioning_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_QtPositioning_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_QtPositioning_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_QtPositioning_qt_metacast;

#endif
