/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.13
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtSensors.h"

#line 42 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtSensors/qdistancesensor.sip"
#include <qdistancesensor.h>
#line 29 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtSensors/sipQtSensorsQDistanceFilter.cpp"

#line 28 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/sip/QtSensors/qdistancesensor.sip"
#include <qdistancesensor.h>
#line 33 "/Users/alan/PycharmProjects/ProjectPyQt/PyQt5_gpl-5.11.3/QtSensors/sipQtSensorsQDistanceFilter.cpp"


class sipQDistanceFilter : public  ::QDistanceFilter
{
public:
    sipQDistanceFilter();
    sipQDistanceFilter(const  ::QDistanceFilter&);
    virtual ~sipQDistanceFilter();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    bool filter( ::QDistanceReading*);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQDistanceFilter(const sipQDistanceFilter &);
    sipQDistanceFilter &operator = (const sipQDistanceFilter &);

    char sipPyMethods[1];
};

sipQDistanceFilter::sipQDistanceFilter():  ::QDistanceFilter(), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQDistanceFilter::sipQDistanceFilter(const  ::QDistanceFilter& a0):  ::QDistanceFilter(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQDistanceFilter::~sipQDistanceFilter()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

bool sipQDistanceFilter::filter( ::QDistanceReading*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,sipName_QDistanceFilter,sipName_filter);

    if (!sipMeth)
        return 0;

    extern bool sipVH_QtSensors_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QDistanceReading*);

    return sipVH_QtSensors_12(sipGILState, sipImportedVirtErrorHandlers_QtSensors_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QDistanceFilter_filter, "filter(self, QDistanceReading) -> bool");

extern "C" {static PyObject *meth_QDistanceFilter_filter(PyObject *, PyObject *);}
static PyObject *meth_QDistanceFilter_filter(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    PyObject *sipOrigSelf = sipSelf;

    {
         ::QDistanceReading* a0;
         ::QDistanceFilter *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QDistanceFilter, &sipCpp, sipType_QDistanceReading, &a0))
        {
            bool sipRes;

            if (!sipOrigSelf)
            {
                sipAbstractMethod(sipName_QDistanceFilter, sipName_filter);
                return NULL;
            }

            sipRes = sipCpp->filter(a0);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDistanceFilter, sipName_filter, doc_QDistanceFilter_filter);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QDistanceFilter(void *, const sipTypeDef *);}
static void *cast_QDistanceFilter(void *sipCppV, const sipTypeDef *targetType)
{
     ::QDistanceFilter *sipCpp = reinterpret_cast< ::QDistanceFilter *>(sipCppV);

    if (targetType == sipType_QSensorFilter)
        return static_cast< ::QSensorFilter *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDistanceFilter(void *, int);}
static void release_QDistanceFilter(void *sipCppV, int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQDistanceFilter *>(sipCppV);
    else
        delete reinterpret_cast< ::QDistanceFilter *>(sipCppV);
}


extern "C" {static void dealloc_QDistanceFilter(sipSimpleWrapper *);}
static void dealloc_QDistanceFilter(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQDistanceFilter *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QDistanceFilter(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QDistanceFilter(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QDistanceFilter(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipQDistanceFilter *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new sipQDistanceFilter();

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::QDistanceFilter* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QDistanceFilter, &a0))
        {
            sipCpp = new sipQDistanceFilter(*a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDistanceFilter[] = {{59, 255, 1}};


static PyMethodDef methods_QDistanceFilter[] = {
    {SIP_MLNAME_CAST(sipName_filter), meth_QDistanceFilter_filter, METH_VARARGS, SIP_MLDOC_CAST(doc_QDistanceFilter_filter)}
};

PyDoc_STRVAR(doc_QDistanceFilter, "\1QDistanceFilter()\n"
"QDistanceFilter(QDistanceFilter)");


static pyqt5ClassPluginDef plugin_QDistanceFilter = {
    0,
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtSensors_QDistanceFilter = {
    {
        -1,
        0,
        0,
        SIP_TYPE_ABSTRACT|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QDistanceFilter,
        {0},
        &plugin_QDistanceFilter
    },
    {
        sipNameNr_QDistanceFilter,
        {0, 0, 1},
        1, methods_QDistanceFilter,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QDistanceFilter,
    -1,
    -1,
    supers_QDistanceFilter,
    0,
    init_type_QDistanceFilter,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDistanceFilter,
    0,
    0,
    0,
    release_QDistanceFilter,
    cast_QDistanceFilter,
    0,
    0,
    0,
    0,
    0,
    0
};
